mdn/content

README.md, package.json, yarn.lock
How to test it...
1. Check out the branch and assert that you can still run `yarn start` happily even if you don't yet have a `.env` file. 
2. Follow the instructions in the README and attempt to set it to something different.
=> how to set your $EDITOR

.github/workflows/preview.yml, files/en-us/mdn/kitchensink/index.html
Part of #7
I'll share more about how I built this later. 
Can you please review the macros used and think of some that aren't used? @schalkneethling @escattone
=> A kitchensink page

LICENSE, LICENSE.md
@chrisdavidmills @peterbe This is my first crack at a `LICENSE.md` file for this content repo. It would apply to the upcoming `archived-content` and `translated-content` repos as well.
=> add licenses for content

package.json
Per https://docs.npmjs.com/files/package.json#license:
> If you are using a license that hasn’t been assigned an SPDX identifier, or if you are using a custom license, use a string value like this one:
> 
> ```json
> { "license" : "SEE LICENSE IN <filename>" }
> ```
> 
> Then include a file named <filename> at the top level of the package.
=> fix license in package.json

CONTRIBUTING.md
Fixes https://github.com/mdn/yari/issues/1108
This is my initial take, with help from @chrisdavidmills and @peterbe, on the guide for content contributors.
@chrisdavidmills and/or @ddbeck Feel free to take this over from here. 😄 I probably shouldn't be writing this document in the first place, but I at least wanted to give it a kick start (with lots of organizational help from @chrisdavidmills )!
I wrote the `git` commands from the point of view that `origin` is the remote name for the user's fork (e.g, https://github.com/octocat/content). I realize that others do the opposite, where `origin` is the remote name that refers to the main repository (https://github.com/mdn/content). I'm never sure which approach is considered best for documentation.
=> add initial document for contributors

CONTRIBUTING.md
I noticed a few cases where I had too many `)`'s, and thanks to @schalkneethling for [spotting an issue in the `Deleting a document` section](https://github.com/mdn/content/pull/35#discussion_r502804677).
=> minor fixes

files/en-us/web/html/element/main/index.html
Removed the tag `HTML grouping content` from the `en-us/web/html/element/main/index.html` file as it is only referenced in `en-us/web/html/element/index.html`. This removes a duplicate `<main>` entry that was placed under the `Text Content` heading.
=> Main tag under incorrect heading

files/en-us/web/javascript/reference/operators/super/index.html
Removed some empty constructors since they didn't call super().
Did it already in the wiki but wanted to try it here on GitHub as well.
https://github.com/mdn/sprints/issues/2858
=> Removed constructors that didn't call super

.github/CODEOWNERS
This also fixes a bug where the `/*` was last so it took precedence for all root-level files.
=> fix codeowners to play nice with auto-merge

.github/workflows/pr-build.yml, files/en-us/mdn/kitchensink/index.html
Fixes #1604
BEFORE:
[AFTER (Cold cache)](https://github.com/mdn/content/pull/111/checks?check_run_id=1406997467)
[AFTER (Warm cache)](https://github.com/mdn/content/pull/111/checks?check_run_id=1407020436)
So, if we get 19.2 PRs (just for en-US) per day, that means it would have cost 19.2 * 1m21s of total `yarn install` time every day. Now it's 19.2 * 17s instead. 
This stuff matters. It's much better for the environment and it gives much speedier feedback to the PR creator to know if her PR passes CI.
=> use node_modules/@mdn/yari to build PR builds

.github/workflows/preview.yml
This Action does not use the diff, just the fact that at least one of three specific files changed, so it's possible to use only built-in scripting tool [`on.pull_request.paths`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths).
=> GitHub Actions: remove get-diff-action from preview

.gitignore
This doesn't really matter in production (or dev or stage) builds because there it doesn't matter what's left after the build. BUt it's inconvenient to have to see this after you run `yarn dev` in Yari based on your CONTENT_ROOT.
=> ignore _githistory.json

.github/workflows/pr-build.yml, .github/workflows/pr-check_redirects.yml
This PR is a follow-up to #137.
Highlights:
- Extract `check_redirects` job into a separate file for clarity and to specify separate `on.pull_request.paths`.
- Remove `technote-space/get-diff-action` from `check_redirects` job (because it's no longer needed)
- Update `technote-space/get-diff-action` in `build` job, remove all the `if: steps.git_diff_content.outputs.diff` because if job is run either there is a diff or the GitHub Action was updated and should to be tested.
This PR makes these GitHub Actions run only if they need to (as opposed to using > 10 seconds per job on setting up the job, checking out the repo, finding no diff and skipping all the checks).
(Force-pushed to add a commit signature.)
=> GitHub Actions: split pr-build.yml, update get-diff-action

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.html
There's `max-width: 100%;` in the global CSS that's causing abnormal aspect ratio when used together with fixed width and height of images. Setting the height to `auto` should fix that.
=> Fix image aspect ratio

files/en-us/learn/forms/your_first_form/index.html
Because of the dir="rtl" attribute, the code is rendered "smashed" to the right side. This attribute doesn't make sense for code listings. Remove it to make the code legible again.
=> Remove right-to-left attribute from code listing

files/en-us/tools/accessibility_inspector/index.html
The images on this page are stretched because their height is not match their aspect ratio. By removing their height, it fixed them.
=> Change images height to preserve aspect ratio

files/en-us/learn/server-side/django/skeleton_website/index.html
- Removed some bold styling in code block because it wasn't working - see https://github.com/mdn/yari/issues/2198
- Removed empty spaces after full stop: `. </p>`
- Fixed up some list layout issues.
=> Fix some layout problems with Django skeleton page

files/en-us/learn/css/building_blocks/styling_tables/index.html, files/en-us/learn/forms/advanced_form_styling/index.html, files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.html
This change replaces all instances of “styleable” in MDN content with “stylable”. Otherwise, without this change, the content is inconsistent in that some articles have “stylable” while others have “styleable” (and we even have one article which uses both “stylable” and “unstyleable” within the same article).
---
https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling is the article that has both “stylable” and “unstyleable”. (I noticed it while looking at https://github.com/mdn/content/issues/396.)
I don’t have any strong opinion about “stylable” being better than “styleable” — so this patch could actually be amended to do the reverse, if we decide that’s better.
The reasons I chose “styleable” is that there are slightly more instances of it in existing MDN content, …
=> Normalize on “stylable” (not “styleable”)

files/en-us/learn/css/css_layout/practical_positioning_examples/index.html
Fixes #464 the text suggested that the initial containing block was the html element, it's really the root element which is the size of the viewport https://www.w3.org/TR/CSS2/visudet.html#containing-block-details
=> Fixes #464 small error in text of positioning learn material 

files/en-us/learn/css/building_blocks/backgrounds_and_borders/index.html
Fixes: #596 
There was a mistake in the order of values for `background-position` as reported. Also fixed fixable flaws while I was in there (links and code example syntax).
=> fixing error and other flaws

files/en-us/learn/server-side/django/models/index.html
Fixes #463
This changes code so that book cannot be deleted until no bookinstances reference it. As part of this I explained the default delete option (cascade).
=> Django - fix up on_delete options and explanation

package.json
Since this is currently all content, I don't think the difference between devDependencies and dependencies is a big deal. Also marked `private` since it's not a published package
=> chore: Push devDepenencies and mark private

files/en-us/learn/common_questions/index.html
Fixes #1130
The links contained in headings were being overwritten by whatever creates permalinks. I'll raise a separate issue for that. I've moved the links out of the headings. They weren't very obviously links as part of the heading anyway so perhaps this is a better approach.
=> Fixing links in common questions

files/en-us/learn/javascript/asynchronous/async_await/index.html
Fixes #1202 
- `newArr` is undefined in the example for async_away.
- `newArr[i]` is also undefined in 309.
=> Fixing two statements with undefined variables in an example for async_await

.github/CODEOWNERS
I've gotten agreement from one of our community members to review SVG-related PRs, so I've created a yari-content-svg team, added him to it, and added it to the CODEOWNERS file. 
Does this look OK?
=> adding SVG review team

files/en-us/learn/javascript/first_steps/strings/index.html
let creates error message: Uncaught SyntaxError: redeclaration of let badString
=> Removed "let" from "let badString = string;"

.editorconfig
Went with the main style I could see which was more single/double with spaces.
Didn't do any formatting afterwards, but will be respected in IDEs or GitHub editor going forward
=> chore: Add initial EditorConfig for whitespace

package.json
Currently generates inside "node_modules" with get's reset after yarn installs
The `build` folder is already in `.gitignore`
=> chore: Put build output in local build folder

files/en-us/learn/javascript/building_blocks/looping_code/index.html
I made this change as I think it improves readability (as 'if' is so small and can be missed, causing confusion) and since the 'if' is a code keyword like <code>continue</code>, <code>num</code> and <code>!==</code> in the same paragraph, it provides consistency.
=> Put reference to if statement in <code> brackets

files/en-us/learn/javascript/objects/object_prototypes/index.html
Correct the example illustrating that the prototype object of an instance is not the same object as the prototype object of its constructor function.
=> fix: a JavaScript instance and a constructor function have different prototype objects

files/en-us/learn/performance/multimedia/index.html
The purpose of this change was to clarify that AVIF image is now supported in Firefox (and not just chrome as indicated). While I was here I added cross links to the [Image types and format guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) which I see as the "master" doc on images.
I also improved a little of the English. This could be made more readable, but decided to limit myself for now. It does have lots of useful info.
=> Minor subedit of Learn>Performance>Multimedia

files/en-us/tools/web_console/helpers/index.html
Current page does not contain a `#title` element anymore so the example can't be used on it, Change id to class and it works
=> Update Web Console Helpers example

files/en-us/tools/web_console/helpers/index.html, files/en-us/tools/web_console/index.html
There is a non-fixable flaw in that macro exists  `{{deprecated_inline("gecko74")}}`  and should be removed `{{deprecated_inline("gecko74")}}`. What I should I replace it with?
Doing this in preparation for fixing https://github.com/mdn/content/issues/1729
=> Web console flaws

files/en-us/learn/getting_started_with_the_web/html_basics/index.html
I don't think we gain much by dwelling on what HTML is not; we're here because we want to know what HTML *is*, so let's jump straight into that 😄 
I can see how at the time of writing the statement may have been written to make HTML seem approachable or less intimidating maybe. But I've also seen this sentiment bandied about widely to belittle front-end developers, or draw lines in the sand between people who work on markup and styles and people who do "real programming", whatever that means. I don't think that's something we really want to echo or get drawn into here.
=> Remove assertion that HTML is not a programming language

files/en-us/web/svg/attribute/font-size-adjust/index.html
This ad-hoc navigation bit is unnecessary, and breaks the identification of the `summary` field in the index.json output.
=> Drop SVG font-size-adjust ad-hoc navigation cruft

files/en-us/learn/server-side/express_nodejs/introduction/index.html
The express tutorial linked to http://hotframeworks.com/, which has since closed down (i.e. domain is now up for sale). I've removed the link and made the tutorial sane.
Fixes #1976
=> Fix a link that is no longer valid

files/en-us/learn/server-side/django/home_page/index.html
=> Fix UK -> US English spelling, "recognize"

files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html, files/en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.html, files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html, files/en-us/learn/javascript/building_blocks/conditionals/index.html, files/en-us/learn/javascript/building_blocks/looping_code/index.html, files/en-us/learn/javascript/first_steps/arrays/index.html, files/en-us/learn/javascript/first_steps/useful_string_methods/index.html
I didn't test it because I have a problem with a yari dependency (gifsicle).
[Mdn article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods##fixing_capitalization)
Pressing `tab` in playable code causes :
> Playable_code_2:172 Uncaught TypeError: Assignment to constant variable.
at insertAtCaret (Playable_code_2:172)
at HTMLTextAreaElement.textarea.onkeydown (Playable_code_2:157)
=> Use 'let' so assignment is not broken

files/en-us/learn/css/howto/generated_content/index.html, files/en-us/learn/html/howto/author_fast-loading_html_pages/index.html, files/en-us/learn/server-side/apache_configuration_htaccess/index.html, files/en-us/learn/server-side/configuring_server_mime_types/index.html
The `class="external"` gets automatically injected at build-time anyway so no need to manually set it in the raw sources. 
Besides, this'll make more sense as we move towards something Markdown'ish.
=> remove unnecessary class=external in learn tree

files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html
Changed `id` attribute into small caps otherwise reference at line no 237 with `{{anch("Configure CSP directives")}}` to section `Configure CSP Directives` on same page will not work.
=> Fix reference to Configure CSP directives

files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html
The way this note is written feels pre-html5. With <acronym> dropped from the HTML spec, it should be treated like a historical note.
=> Clarify that <acronymn> is deprecated

files/en-us/learn/css/css_layout/positioning/index.html
Replace the noun “ascendant” (which is usually an adjective and only very rarely used as an antonym for “descendant”) with the much more commonly understood “ancestor” – as used in the rest of this article.
=> Update index.html - to make it more understandable to native and non-nativeEnglish speakers

files/en-us/learn/html/introduction_to_html/getting_started/index.html
If there are other reasons, I recommend they be linked, or explicitly defined.
The "other reasons" had me doing some curious web searching, but nothing I found felt compelling enough that I felt it should be added here.
Consequently, this PR suggests removing those words.
=> Remove unclear "other reasons"

files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.html
Service Workers shipped in Safari 11.1 as confirmed in our own BCD https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker, so removing this outdated note.
=> remove outdated note

files/en-us/learn/css/howto/create_fancy_boxes/index.html, files/en-us/learn/css/howto/index.html
I have written quite a few of these small examples now so I figured it time to revamp the listing page.
I've removed links to things that essentially dumped people into a page of content with no context, moved links to relevant guides and tutorials up under the sections, then linked in my new content with some description. I've kept them grouped as "text styling", "layout" and so on, as it makes it easier to list useful things.
I have a few more to write but I can add them as I go.
=> How to CSS index page

files/en-us/learn/javascript/objects/object_prototypes/index.html
The information was incorrect - I have amended the note with the correct 'what is the difference between the prototype and prototype property'
See https://github.com/mdn/content/issues/2200
=> prototype note fix

files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.html
revise copy for **Auditing tools** example using Wave
In the **Auditing tools** section, I noticed the [Wave website](https://wave.webaim.org/) changed in a way that required an update to the instructions for the example. I removed references to an _Analyse Your Website_ button that no longer exists and revised other related wording.
=> Revise Auditing tools example

files/en-us/web/svg/attribute/textlength/index.html
- Move misplaced `</div>` end tag that breaks rendering; see
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength
- Fix broken macro ref for undocumented `newValueSpecifiedUnits()` method
=> Fix problems with SVG textLength doc

files/en-us/learn/forms/test_your_skills_colon__form_validation/index.html
Found a typo error on Test-your-skills-Form-structure, 'This' on line 14 is changed to 'The'.
=> Fix typo in “Test your skills: Form structure”

files/en-us/learn/javascript/objects/inheritance/index.html
Fixes https://github.com/mdn/content/issues/2791
=> Drop old text about limited support for classes in JavaScript

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.html
Simple typo: the list of existing framework tutorials wasn't updated to have the Svelte tutorial.
=> Typo: add Svelte tutorial to the list

files/en-us/learn/server-side/django/admin_site/index.html
organise -> organize 
except for the CSS ID _Organise_detail_view_layout_
=> Update spelling to en-US: "organise"->"organize"

files/en-us/learn/html/howto/use_data_attributes/index.html
Removed redundant parentheses  from CSS `attr()` function reference.
=> Removed redundant parentheses

files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.html
Fixes https://github.com/mdn/content/issues/2593
The Three.js docs structure has changed at some point, resulting in broken links. I've fixed all of those in this PR.
=> fixing broken Three.js links

files/en-us/learn/server-side/django/models/index.html
This corresponds to fix https://github.com/mdn/django-locallibrary-tutorial/pull/89
Basically this should not be needed because it should not be possible to get to a state where a bookinstance has no book. Django don't believe that though, so makemigrations fails. This fix just captures what you need to do to get this to work.
=> Fix Django BookInstance.book model to have null default value

files/en-us/learn/javascript/first_steps/strings/index.html
Fixes https://github.com/mdn/content/issues/2959
=> Fix “Handling text — strings in JavaScript” typo

.github/workflows/markdown-lint.yml, rfcs/aria-roles.md
As part of the MDN opportunity assessment process, we are intending to create RFCs to explain a suggested larger stream of work that we want to work on. This is the first of those RFCs.
---
Checklist — To help your pull request get merged faster, please do following:
1. - [ ] Provide a summary of your changes — say what problem you are fixing, what files are changed, what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for …
=> add initial rfc to repo

.github/PULL_REQUEST_TEMPLATE
=> grammar fix in PULL_REQUEST_TEMPLATE

.github/workflows/pr-check_redirects.yml, .github/workflows/preview.yml
Now we're using the same technique to cache `node_modules` in all PR workflows that depend on `yarn install`.
=> cache node_modules the same in all workflows

files/en-us/learn/javascript/asynchronous/async_await/index.html
There is no need to use a if-else conditional statement when the if branch contains a "throw" clause inside as no statements get executed after that. Keeps the code smaller, clean, less indentation, and more readable.
If this change gets approved you might want to consider search for this pattern on the different files of the MDN guide as it is not the first place I saw it.
=> Drop unneeded “else” after “throw” in “async and await” how-to

files/en-us/web/svg/attribute/accent-height/index.html, files/en-us/web/svg/attribute/accumulate/index.html, files/en-us/web/svg/attribute/additive/index.html, files/en-us/web/svg/attribute/alignment-baseline/index.html, files/en-us/web/svg/attribute/alphabetic/index.html, files/en-us/web/svg/attribute/amplitude/index.html, files/en-us/web/svg/attribute/arabic-form/index.html, files/en-us/web/svg/attribute/ascent/index.html, files/en-us/web/svg/attribute/attributename/index.html, files/en-us/web/svg/attribute/azimuth/index.html, files/en-us/web/svg/attribute/index.html, files/en-us/web/svg/index.html
More to come :-)
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> Clean up flaws and indents of SVG/attributes/a

files/en-us/learn/tools_and_testing/understanding_client-side_tools/deployment/index.html
optimise -> optimize
summarise -> summarize
=> revise text for US English spelling

.github/workflows/pr-test.yml, files/en-us/mdn/kitchensink/index.html
As of this change, any touch of any index.html that introduces something that's supposedly "unsafe" should crash CI.
=> fail on unsafe html

files/en-us/web/svg/attribute/stop-opacity/index.html
Changed compatibility data source on [this page](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop) from `svg.attributes.presentation.stop-opacity` to `svg.elements.stop.stop-opacity`.
This is following the suggestion that SVG compatibility data should be organized the same way HTML is: https://github.com/mdn/browser-compat-data/issues/9462
Which in turn is following discussion here about missing compatibility data for `stop-opacity`: https://github.com/mdn/browser-compat-data/issues/9402
=> Switch to different svg compat data (mdn/browser-compat-data#9402)

files/en-us/learn/css/first_steps/getting_started/index.html
1. - [x] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [x] Review the results of the automated checking we run on every PR and fix any problems reported (see the …
=> Add span element to sample code

files/en-us/learn/getting_started_with_the_web/javascript_basics/index.html
Fixes https://github.com/mdn/content/issues/3158
1. - [ ] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [ ] Review the results of the automated checking we run …
=> Make string building code consistent

files/en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page/index.html
This change fixes a typo in the templating. It currently shows the title of the book twice.
I changed the template so it shows `Title` instead like the screenshot in the tutorial.
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page/locallibary_express_book_detail.png
Changed `#{title}: #{book.title}` to `Title: #{book.title}`
1. - [x] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". …
=> Fix Title in Book Detail View

files/en-us/learn/css/first_steps/using_your_new_knowledge/index.html
A reader found the text in https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge ambiguous. It isn't, but this makes it a tiny bit easier to read. See #3322
=> Fix nit in CSS using your knowledge

files/en-us/learn/css/css_layout/responsive_design/index.html
Update @viewport description to clarify that it has been deprecated and should not be used.
=> @viewport has been deprecated

files/en-us/web/svg/attribute/stroke-linejoin/index.html
Fixes a typo in https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin#miter-clip and https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin#arcs
below vs bellow
I checked to make sure this wasn't an English vs American spelling - and am pretty certain it's just a mistake.
1. - [x] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number …
=> Fix typo in stroke-linejoin

files/en-us/web/svg/attribute/markerunits/index.html
The markerUnits attribute defines the coordinate system for the markerWidth and **markerHeight** attributes, not markerWidth and **markerUnits** as is currently reflected in the docs. This commit changes the docs to match the [SVG 1.1](https://www.w3.org/TR/SVG11/painting.html#MarkerUnitsAttribute) and [SVG 2](https://svgwg.org/svg2-draft/painting.html#MarkerUnitsAttribute) specs.
1. - [x] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [x] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". …
=> Fix incorrect references in markerUnits docs

files/en-us/learn/server-side/django/authentication/index.html, files/en-us/learn/server-side/django/skeleton_website/index.html
Fixes #2555
Fixes #2836
Fixes #3368
The authentication code relies on an OS import, which this adds into instructions. Note that the module is imported in the deployment module too which occurs later. I have made a conscious decision NOT to change that doc - multiple imports of that same module will do not harm to the tutorial, and this simplifies the instructions.
I also removed the import from the skeleton because it is not needed there (ie why modify the skeleton code generated by Django unless it is broken!)
=> Django server tutorial - as os module import

rfcs/README.md
Adding README to the RFCs folder, to explain the process of submitting them, what they are for, etc. Fixes https://github.com/mdn/pab/issues/82
=> adding RFCs explainer readme

files/en-us/tools/page_inspector/how_to/examine_and_edit_css/index.html
In Examine and edit CSS Page, under Browser compact Warning heading, in (open about.config in the URL bar to view/set Firefox preferences) about.config should be about:config.
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS
Fixes Issue #3441 
=> Fixes a typo in "Examine and edit CSS":

files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.html
There was nothing wrong. I've just added some content I thought could be useful for the reader. Before the "DNS explained" section, I've added a section explaining the order in which the component files are parsed by the server. While the user is really studying frontend tech with these chapters, I think it's important to figure out how the server processes these files.
> MDN URL of main page changed: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
> Issue number (if there is an associated issue): none 
=> Add: section on component files order

files/en-us/learn/accessibility/html/index.html
`pre` tag was lacking syntax highlighting
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#text_alternatives
Before:
After:
=> brush html in HTML code snippet

files/en-us/tools/page_inspector/how_to/examine_event_listeners/index.html
Change the order of elements describing the pop-up to reflect whats shown in the image.
The description list order doesn't reflect whats shown in the example image.
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_event_listeners
=> fix[tools]:list elements order (minor)

files/en-us/learn/server-side/first_steps/introduction/index.html
Issue in [<strong>Are server-side and client-side programming the same?</strong>](https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction#are_server-side_and_client-side_programming_the_same): 
[...] examples of popular server-side web languages include PHP, Python, Ruby, C#, and NodeJS (JavaScript).[...]
It is a good idea to replace "NodeJS (JavaScript)" by "JavaScript (NodeJS)". I see many people thinking NodeJS is a language. Node is a runtime. JavaScript is the language.
https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction
#3568
=> Changing NodeJS(Javascript) to Javascript(NodeJS)

files/en-us/learn/css/first_steps/what_is_css/index.html
The browser support section in https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS shows the compat table and then has text that refers to it (even though the text is intended to go first). This is caused by the macro, which floats the content up.
I have chosen to fix this by splitting the compat section under its own heading. This is a little unnatural from a flow point of view but about the right effort for the benefit :-)
Fixes #3609
=> Fix up css compat layout

files/en-us/learn/server-side/django/deployment/index.html
Fixes #3480 (just removes a comment). This should NOT cause a problem, but for some reason it does.
=> Django - remove incorrect comment using os.path

files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.html
Link without scheme was pointing to internal `Page not found`.
=> Fix broken link

files/en-us/learn/javascript/first_steps/what_went_wrong/index.html
Made use of let keyword and replaced var in the example.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong#syntaxerror_missing_before_statement
Fixes #3641
=> Match “Troubleshooting JavaScript” w/ example code

.github/workflows/system-file-changes.yml
First real use of the system-file-changes workflow that makes sure any PR fails that contains too-sensitive changes.
=> oops remove leftover comment in system-file-changes.yml

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
There were grammatical errors on the page and they could be misleading.
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started
Added the appropriate punctuation marks where necessary.
On line 130, I changed the first word, This, to 'this' because the preceding list items start in lower case.
On lines 161 and 166, I changed the word, app, to 'App' because that's how it actually appears by default after creating a new Vue app with the Vue CLI.
=> fix grammatical errors on 'Getting Started with Vue' page

files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
Considering the given example in the previous sentence, the changed sentence is not correct logically in original form. So I tried to change it to give a more clear meaning.
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS#min-_and_max-_sizes
=> Revise CSS “min- and max- sizes” doc, for clarity

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.html
> 'Improves' in the middle of the statement should begin with a lowercase.
> MDN URL of main page changed: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#tooling
=> Fixed 'Improves' -> 'improves' in the middle of a statement

files/en-us/learn/css/styling_text/web_fonts/index.html
Fixed link to `#Web_safe_fonts`. The incorrect casing caused it to not work in Chrome (and likely other browsers, too).
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts
=> Fix broken document fragment link

files/en-us/learn/javascript/client-side_web_apis/manipulating_documents/index.html
Seems like a word was missing.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#active_learning_basic_dom_manipulation
I assume this is what the author meant. See also: https://stackoverflow.com/questions/26848289/javascript-queryselector-vs-getelementbyid
=> Fix missing word in “Manipulating documents” article

rfcs/webview-information.md
In the previous browser compat data project meeting, we decided that it would be good to add information to MDN on dealing with WebView environments, from the perspective of a web developer trying to support them in their apps/sites. This RFC aims to define that work.
n/a
n/a
n/a
=> adding rfc for webview information

files/en-us/learn/server-side/django/deployment/index.html
- What was wrong/why is this fix needed? (quick summary only)
nit:
> 'When this operation completes, you should be able to go back to the page on Github where' 
is written twice
- MDN URL of main page changed
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment
- Issue number (if there is an associated issue)
- Anything else that could help us review it
=> [django/deployment] nit: doubled line

files/en-us/learn/server-side/django/forms/index.html
- What was wrong/why is this fix needed? (quick summary only)
In Django Tutorial Part 9 'Working with Forms' in section 'Renew-book form using a Form and function view'/'The template' there is:
`<p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>`
While I believe it should be:
`<p>{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>`
- MDN URL of main page changed
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
- Issue number (if there is an associated issue)
- Anything else that could help us review it
=> [Django/Forms] nit: missing '>' in '<p>'

files/en-us/learn/server-side/django/testing/index.html
Hi,
Below a couple of NIT ideas for small improvements in Django Tutorial Part 10 'Testing a Django web application' considering PEP 8 guidelines.
- What was wrong/why is this fix needed? (quick summary only)
1. In section 'LocalLibrary tests'/'Forms' there is:
`self.assertTrue(form.fields['renewal_date'].label == None or form.fields['renewal_date'].label == 'renewal date')`
While I believe there should be:
`self.assertTrue(form.fields['renewal_date'].label is None or form.fields['renewal_date'].label == 'renewal date')`
Comparison with None performed with equality operator. That type of compression should be done with 'is'. PEP 8: comparison to None should be 'if cond is None'.
2. In section 'LocalLibrary tests'/'Models' there is:
```
def test_date_of_death_label(self): …
```
=> [django/testing] nit: PEP 8

files/en-us/learn/server-side/django/sessions/index.html
Fixes up docs to reflect this change in example: https://github.com/mdn/django-locallibrary-tutorial/pull/90 (adds explanation of how to use the `pluralize` tag.
There was also code saying "look at the changes shown in bold", but the bold in code blocks does not render. So this works around that problem.
=> Add info about pluralize tag and fix use of strong

files/en-us/learn/javascript/first_steps/strings/index.html
The expression Math.round((examScore/examHighestScore*100)) had double opening and closing brackets instead of single ones. The additional ones are redundant and could cause confusion. They should be changed to single opening and closing brackets.
The expression Math.round((examScore/examHighestScore*100)) had double opening and closing brackets instead of single ones. The additional ones are redundant and could cause confusion.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
=> Change double brackets to single brackets

files/en-us/web/svg/attribute/transform-origin/index.html
Related: https://github.com/mdn/browser-compat-data/issues/9834
=> Add Compat table to SVG “transform-origin” doc

files/en-us/learn/javascript/asynchronous/timeouts_and_intervals/index.html
checking if `rotateCount > 359` was unnecessary, as `rotateCount%=360` gets a value between 0 and 359 irrespective
https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/timeouts_and_intervals/index.html
=> Replace redundant code in “Timeouts and intervals” doc

.github/workflows/pr-review-companion.yml
Part of #4165
I've never see this come up before. I googled the problem and lots of `poetry` users seem to get this and it's confusing. 
This PR will fix it but it would be nice to be able to cache the `poetry install` so I'm not going to close the issue yet.
=> hotfix to unbreak poetry in PR Review Companion

.github/workflows/pr-review-companion.yml
Fixes #4165
@Elchi3 Watch out! I'm going to self-merge this and see if it solves all the problems. 
I got the tip for this smart solution in https://github.com/snok/install-poetry/issues/29
We were caching the virtualenv across two different versions. This might bite us again on the next release. But my mitigation is to add a code comment to remind us of what needs to be done when a new version comes out.
=> cache the poetry install based on the action version

files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.html
The documentation at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage under the "A more involved example" tutorial currently refers to the index.js file at line 40 in file personal-greeting.html. However, it looks like the index.js file is actually being referenced on line 41.
=> Remove specific line reference to script tag in HTML file

files/en-us/learn/server-side/django/generic_views/index.html
Fixes #4112
Essentially calling get_absolute_url on the model means that you can get the URL of a model instance from just one place and in the same way across Django code and templates. That means your code looks more consistent, and also that if you need to change it, you do it in one place. All better for maintenance. 
Associated code fixes in https://github.com/mdn/django-locallibrary-tutorial/pull/91
=> Clarify why get_absolute_url is better

rfcs/aria-roles.md
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
@chrisdavidmills asked me to list all ARIA roles that lack a dedicated page in https://github.com/mdn/content/issues/3924#issuecomment-815559861.
N/A
#3924
I compared each role in https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques#document_structure_roles with https://www.w3.org/TR/wai-aria-1.1/#roles_categorization
=> List missing ARIA roles in MDN. Refs #3924

files/en-us/learn/css/css_layout/grids/index.html
Fixes #4127 
Learn CSS page still had mentions of `grid-gap`, I've changed them all other than the note which explains the prefixed versions.
=> fixing prefixed gap properties

files/en-us/learn/css/building_blocks/organizing/index.html
Part of https://github.com/mdn/yari/issues/3564
The Yari flaw fixer couldn't even find the code in the original document because it contained a nullbyte character. I manually removed the nullbyte character with my IDE, then the "Fix fixable flaws" button could do its thing.
=> removing nullbyte from code snippet so it can be flaw fixed

files/en-us/learn/server-side/django/forms/index.html
Fixes #4258
Note that this was injected by a previous "nit fix" that my checking did not catch (whoops). The companion example code is still good.
=> Remove extra > tag added by previous "nit fix"

files/en-us/learn/learning_and_getting_help/index.html
Due to the missing issue. (Can not find the related issue, thought it is 4068.)
Since menu entrys are most probably links. I added the *a* tag and the *href* attribute to the menu entrys in the unordered list example.
https://developer.mozilla.org/en-US/docs/Learn/Learning_and_getting_help
=> Add the a tag and the href attribute 

files/en-us/learn/server-side/express_nodejs/forms/create_book_form/index.html
Fix small typo "convent → convert"
Fix small typo "convent → convert"
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form
=> Fix small typo "convent → convert"

files/en-us/learn/css/building_blocks/debugging_css/index.html
This is another attempt to fix https://github.com/mdn/content/issues/4000, this time by linking to the table in the reference page. For the details of why this problem is happening, see https://github.com/mdn/content/pull/4026.
@sideshowbarker , I'm sorry I didn't fully read your PR description before commenting, or I would have seen that you'd already considered and rejected the option of linking to the table. Still this seems like a more obvious option, although I agree that making people navigate to a different page is not ideal.
=> Fix misplaced compat table

files/en-us/learn/server-side/express_nodejs/forms/index.html
Fixed express-validator documentation links
Documentation links for express-validator need to be fixed (they're directing to wrong documentation).
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms
=> Fixed express-validator documentation links

files/en-us/learn/tools_and_testing/cross_browser_testing/introduction/index.html
The Introduction to Cross Browser Testing page lists various testing tools but is missing Browserling. I added Browserling to the list for completeness. Browserling is one of the first cloud-based cross-browser testing services, created in 2010.
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction
None.
=> Add Browserling to "Introduction to cross browser testing" page

files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.html
Adds a link to TestingBot's Codeless Automation: https://testingbot.com/features/codeless-automation where people can record and playback automated tests.
Adds an alternative for people looking to do Codeless Automation.
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment
=> Add reference to TestingBot for Codeless Automation

.github/workflows/pr-test.yml
@escattone This is a precursor to being able to analyze the raw git diff in the Deployer pr_analyze.py code. 
Equipped with this file in the `build.zip` we can optionally pass it into the review companion to improve the listing of the external URLs.
I've tested it locally in my fork and downloading the `build.zip` and looking into the `DIFF` file is the same you get in a PR when you look at the diff from that perspective.
=> dump a build/DIFF file for review companion

files/en-us/learn/html/introduction_to_html/marking_up_a_letter/index.html
Fix typo
Typo on the 2nd bullet point of the Inline Semantics section
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter
=> Fix typo in assessment

files/en-us/learn/javascript/asynchronous/timeouts_and_intervals/index.html
The recursive timeout's delay was a bit unclear and hard to understand
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals
=> improve recursive timeout's delay explanation

files/en-us/learn/javascript/client-side_web_apis/video_and_audio_apis/index.html
The <pre> at line 74 did have a class of "brush: html" for styling the html code snippet
=> fixed typo

files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.html
On https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility:
- Remove redundant _"click here"_,
- Change _Jasmin_ to _Jasmine_ for the testing framework.
=> Fix some typos

files/en-us/learn/javascript/asynchronous/timeouts_and_intervals/index.html
The description wasn't precise, it told the reader that requestAnimationFrame was a looping function.
Aside from that, it referred to motivations based in setInterval alone, when it's actually related to all previous async functions.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals
=> improve requestAnimationFrame description

files/en-us/learn/javascript/asynchronous/async_await/index.html
Removes an errant curly bracket from the second example snippet under [this header](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await#rewriting_promise_code_with_asyncawait) on the "Making asynchronous programming easier with async and await" page: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await
=> Remove unpaired curly bracket in async/await example

files/en-us/learn/server-side/express_nodejs/deployment/index.html
Fixes #4503 , and also tidies up Notes to the standard format.
Note, the need for quotation marks has changed several times - i.e. this is not the first time I've toggled what this says. To fix it this time I have removed the marks (that works on my testing on linux and Windows) but also added a note that you might need to add them on some systems).
=> Add note about quotation marks around mongodb url

files/en-us/web/svg/attribute/letter-spacing/index.html
Reported by https://github.com/mdn/content/pull/4664#issuecomment-831067522
The upper case anchor broke the link.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing (below the Usage box)
N/A
N/A
=> lowercase anchor

files/en-us/learn/common_questions/what_is_a_web_server/index.html
Fixes #4679
Changes "Excusing" where they mean "Excluding" and also removes a link flaw that is of no great benefit even if fixed.
=> Fix typo in common questions/what is web server

files/en-us/learn/server-side/django/development_environment/index.html
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment
MacOS Catalina and later use the ZSH shell by default, which uses the .zshrc file as a startup. The main change here is to mention the location of this startup file and that you may need to either set .bashrc or .zshrc. I don't have a mac so I have made the ASSUMPTION that the commands you add to the file are the same, and that it is sourced in the same way.
This also fixes up some mis-use of spans in pre blocks and other minor tidy.
@CreaTorAlexander can you please sanity check?
Fixes #2688
=> Django: Add ZSH info for setting up dev environment

.github/workflows/pr-review-companion.yml
Following https://github.com/mdn/yari/pull/3709 we can now give the review companion a `git diff` file and it will use this to judge external URLs it finds in the built pages.
=> use --diff-file for the pr review companion

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.html
starter template  structure like missing "scripts" description...
so, i fix two things
1. fix starter template  structure in real situation ( after running create starter app commands )
2. fix "scripts" content description and add setupTypeScript.js description
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started
N/A
N/A
=> fix flaws in "Getting started with Svelte" docs

files/en-us/learn/javascript/asynchronous/introducing/index.html
> What was wrong/why is this fix needed?
The text that appears after clicking the button can't be seen without scrolling.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing
> What does this PR do?
Increases the height of the live sample. So that, when the button is clicked, the text that appears can be seen without scrolling.
=> Increases the height of the live sample

files/en-us/learn/server-side/express_nodejs/displaying_data/bookinstance_detail_page_and_challenge/index.html
The current return link at the end of the page [BookInstance Detail page and challenge](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/BookInstance_detail_page_and_challenge) points to the top of the [Express Tutorial Part 5: Displaying library data](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data) page. If readers are at the end of [BookInstance Detail page and challenge](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/BookInstance_detail_page_and_challenge) page, it means that they've finished the tutorial and the backlink they are expecting is **Summary** section of [Express Tutorial Part 5: …
=> Updated return link to point to Summary

files/en-us/learn/javascript/asynchronous/async_await/index.html
In the section "The downsides of async/await", it recommends a pattern of using async/await with promises. However, this pattern could lead to an unhandled promise rejection, as explained in Issue #1445. It's not recommended to use this pattern, as explained in the link to stackoverflow provided on Issue #1445. 
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await
Fixes #1445
I change the title "The downsides of async/await" to "A remark when rewritting code using async/await". I also modified the examples, adding a rejected promise, so that the readers could see immediately …
=> add a warning and fix the example using Promise.all()

files/en-us/learn/css/building_blocks/values_and_units/index.html
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
Hi, There's a link wrapping period at the end of a sentence.
In [line 81](https://github.com/mdn/content/blob/e048641c1539f251c34db0341bcf47c75070d8e8/files/en-us/learn/css/building_blocks/values_and_units/index.html#L81), the last period is a link to `resolution` page: 
Numbers, lengths, and percentages section, table, <dimension> row.
<details>
<summary>MDN Content page report details</summary>
* Folder: `en-us/learn/css/building_blocks/values_and_units`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/values_and_units/index.html
* Last commit: …
=> remove link wrapping period

files/en-us/learn/common_questions/using_github_pages/index.html
Fixes https://github.com/mdn/content/issues/4953.
But IMO we should not document GitHub on MDN, we should just point to their docs: https://pages.github.com/. Maybe I should rework this article to do that instead?
=> Update GitHub pages instructions

files/en-us/learn/css/css_layout/normal_flow/index.html
_one another_ is an object construct where _as_ is followed by a subject construct
[Normal Flow](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow)
minor
I am as old as <ins>she</ins> (*not:* as ~her~)
=> "as one another" is an error

files/en-us/learn/server-side/express_nodejs/skeleton_website/index.html
#5018 indicates confusion about differences between changes for Linux and changes for Windows in the project (they changed the valid Linux code to Windows code). The docs were correct, but not sufficiently clear that this code would not work on Windows.
@chrisdavidmills This fix should be good. Please merge.
=> Express: Clear up Windows vs Linux

files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.html
Fixes #5051
Trivial typo and link-to-self fix.
=> Fix typo in command line crash course

files/en-us/learn/server-side/express_nodejs/mongoose/index.html
Fixes #4996
This issue suggests that `node populatedb mongodbURL` should be  `node populatedb 'mongodbURL'`. That is incorrect - on Windows using no quote or a double quote works, but a single quote fails. I suspect a single quote works on Linux. Rather than specify, this update says that you may need to use one or the other, and let's the user try them all.
=> Add note that you may need to wrap URL in quotes

files/en-us/learn/server-side/django/authentication/index.html
Fixes #4978
Bold markup is no longer rendered in pre tags but the example referred to a line highlighted in bold.
=> Django:Authent - fix see in bold description

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_typescript/index.html
What's Updated: The popularity information of TypeScript according to latest reports and statistics, since some of the links are now dead
Content URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript#why_typescript
=> Update TypeScript popularity information in Svelte Section

files/en-us/learn/tools_and_testing/understanding_client-side_tools/deployment/index.html
Switching over the default branch in the examples to `main` to match current standards. I also wrote a note to explain the switch from `master`, which I tried to not make too outspoken while suggesting that `main` should be the default of choice. By all means feel free to make the note more blunt, and hope this helps :)
The examples are still using "master", which is no longer the default.
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Deployment
N/A
For the note, I used [this article](https://www.zdnet.com/article/github-to-replace-master-with-main-startin …
=> Switch master to main

files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.html
Fixed Issue #3197 
An analogy explaining why packets are small relies on a TCP feature, the connection between two computers, was incomplete. 
There should also have been a point explaining that small packets are easier to be dropped and replaced. 
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
Issue #3197
https://github.com/mdn/content/issues/3197
I have created a new branch Issue#3197 for the Pull Request.
=> Resolved Issue #3197

files/en-us/learn/javascript/building_blocks/build_your_own_function/index.html, files/en-us/learn/javascript/building_blocks/conditionals/index.html, files/en-us/learn/javascript/building_blocks/events/index.html, files/en-us/learn/javascript/building_blocks/functions/index.html, files/en-us/learn/javascript/building_blocks/image_gallery/index.html, files/en-us/learn/javascript/building_blocks/looping_code/index.html, files/en-us/learn/javascript/building_blocks/return_values/index.html
Learn sections have an "In this module" section listing all their modules. That creates a flaw for the current module, which is self linking. This turns the link for the current doc to a strong markup for the Javascript building blocks docs.
=> Fix up self links in javascript building blocks

files/en-us/learn/performance/web_performance_basics/index.html
Fixed up broken links in https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics. Most of these were wanted pages, but there were reasonable alternatives.
Fixes #5263
=> Fix up broken links in web performance basics

files/en-us/learn/getting_started_with_the_web/dealing_with_files/index.html
* '-' is hyphen.
* '–' is en dash.
* '—' the em dash.
* Hyphen, en dash, and em dash are different.
'-' is hyphen instead of dash
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files
=> '-' is hyphen instead of dash

files/en-us/learn/server-side/express_nodejs/development_environment/index.html
1. added a link back to [MDN Intro to Express](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction#introducing_express)
2. text revisions in the intro for clarity
3. removed "X.XX" placeholder text under the Objective section
On this page, I also notice a lack of consistency in referring to Node and in the use of emphasis. To make it easier to review this PR, but I will leave these issues for another PR.
MDN URL
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment
=> add link to Node Dev Environment doc

files/en-us/learn/server-side/django/sessions/index.html
The num_visits already has a +1 on the next line. Therefore, the default for the first visit (when the key does not exist) should be 0 as the next line will make the num_visits = 1.
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Sessions
N/A
The document demonstrates how to show the users the number of visits on the page. When the num_visits key exists in the session, the value is extracted and saved in a variable. However, when the num_visits key does not exist (potentially user's first visit), the value returned to the user is 2 instead of 1 as the default value extracted is 1 and 1 …
=> Fix problem with num_visits count in Django Tutorial doc example

files/en-us/learn/javascript/first_steps/strings/index.html
There is an extra word .
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
=> Fix typo in “Handling text — strings in JavaScript” doc

files/en-us/tools/validators/index.html
The /en-US/docs/Tools/Validators page had a number of outdated links, and made unnecessary use of headings for each tool it linked to. This change pares it down to a bulleted list of currently relevant resources. The page can subsequently be built back up with further links other current resources. Fixes https://github.com/mdn/content/issues/4659.
=> Streamline /en-US/docs/Tools/Validators

files/en-us/tools/network_monitor/request_details/index.html
There is no longer any Params tab in the Network pane in Firefox devtools.
Fixes https://github.com/mdn/content/issues/5480.
=> Drop outdated info on Params tab in devtools Network pane

files/en-us/learn/server-side/django/home_page/index.html
changed from `catalog.models` to `.models` consistent with Django official tutorial and https://github.com/mdn/django-locallibrary-tutorial
import statement throws `Import "catalog.models" could not be resolved Pylance` when using Visual Studio Code
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Home_page#view_function-based
fixes #5464 
import statement given by Django:
https://docs.djangoproject.com/en/3.2/intro/tutorial03/#write-views-that-actually-do-something
and https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/views.py
using `from .models import ---` …
=> fix import statement `.models`

files/en-us/learn/html/tables/advanced/index.html
A `<th>` was not marked as code.
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
Fix #5497
=> Codify <th> in Learn/HTML/Tables/Advanced

files/en-us/learn/forms/form_validation/index.html
Made punctuation changes to end of line comments (inserted commas) starting in line 588. No code changes were made.
=> Punctuation fixes in “Client-side form validation” code comments

files/en-us/learn/javascript/first_steps/math/index.html
There were some grammar errors.
> MDN URL of the main page changed:
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
=> Fix grammar error and delete extra space

files/en-us/tools/tools_toolbox/index.html
Fixes #5242
https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox
Some rapid changes in web developer tool location. Text omitted some variants:
- FF89/90: Menu > More Tools > Web Developer Tools
- FF88: Menu > Web Developer > Web Developer Tools
- FF87 (ish): Menu > Web Developer > Toggle Tools
This just makes it clear that before ff88 the top level menu folder might be different.
=> Toolbox doc: Toggle tools removed in FF88

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
The shortcut for a quick fix in VS Code is Ctrl +. not Ctrl + +
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_Todo_list_beginning
=> Fix minor typo

files/en-us/learn/forms/sending_forms_through_javascript/index.html
This link already exists two lines above and does not make sense here.
https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript
=> Remove strange link

files/en-us/web/svg/attribute/viewbox/index.html
=> Remove stray backtick in viewBox documentation

files/en-us/tools/accessibility_inspector/index.html
There were three typos in the Accessibility Inspector documentation.
https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector
n/a
n/a
=> Fixed typos in Accessibility Inspector documentation

files/en-us/learn/css/building_blocks/the_box_model/index.html
Fixes: #5919 by adding a clarifying sentence. I also reduced the height of some of the examples that were causing extra white space.
=> Adds a clarifying sentence

.github/PULL_REQUEST_TEMPLATE
The URLs become clear when the PR review companion comments. And if a PR touches some other file that don't relate to specific pages, the question (still) doesn't make sense. 
Also, I added a lot more space between each question because if you don't have 1 empty line between each question and each answer, they get globbered together.
=> Remove question about MDN URL

files/en-us/web/svg/element/view/index.html
Fixes https://github.com/mdn/content/issues/6131
---
It seems that interactive SVG features won’t work for an SVG image if the SVG markup is put directly into an HTML document — and instead, the SVG image needs to be embedded using an `object` or `iframe` element.
=> Fix interactive SVG example in SVG <view> doc

files/en-us/learn/getting_started_with_the_web/css_basics/index.html
Fixes #6143 removes incorrect statement about margins. The auto margin case is a bit different, but not one to go into in this quick overview of CSS. So it's now correct without over explaining. 
Also fixed a link, and some notes while I was in there.
=> fixing incorrect information about margins

files/en-us/learn/performance/multimedia/index.html
Fixes #6201
Despite the official note Safari 14 is not compatible with webp on macOS desktop. This is noted at the end of https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#webp
This moves that same note into the learn topic https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia#the_most_optimal_format
So basically now it says supported on all major browsers except this one browser in the current version.
=> Add note about Safari 14 on macOS desktop not being compatible

files/en-us/learn/html/tables/advanced/index.html, files/en-us/learn/html/tables/basics/index.html, files/en-us/learn/html/tables/structuring_planet_data/index.html
This PR helps enable https://github.com/mdn/yari/issues/3783.
In that issue I'd like us to use `.standard-table` styling by default. But this will change the appearance of tables that don't current use that class. In almost all cases I don't expect this will be a problem, but in the part of the Learn area that deals with tables there are a few places that we show some markup, then say something like "this will look something like this", and then use a `<table>` directly in the page to show it.
At the moment those tables get pretty minimal styling, so it might look weird if they suddenly start getting the "nice" `.standard-table` style. In any case I think it is a bit of an anti-pattern to show the effect of some markup like this, as we really ought to separate the site's own presentation …
=> Use live samples for sample table output

files/en-us/learn/css/building_blocks/debugging_css/index.html
Subject very agreement. "The property and value is supported" -> "The property and value ARE supported"
Looks like the ID of the h3 will need to be updated to, but hopefully that will be automatic...
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Debugging_CSS
=> Small language change in “Debugging CSS” doc

files/en-us/learn/css/building_blocks/the_box_model/index.html
https://github.com/mdn/content/pull/6278 caused the “The·box·model” article to end up with a navigational hyperlink to itself.
This change corrects the flaw by changing the hyperlink to **The box model [this article]** as plain text.
=> Fix flaw in “The box model” doc

files/en-us/tools/responsive_design_mode/index.html
The description of handling screenshots should be under the Camera's description, but currently it is under the Orientation's.
=> Move the description of downloading screenshots

files/en-us/learn/css/building_blocks/images_media_form_elements/index.html
Make the code snippet easy to read.
At the [reset CSS code block](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements#putting_it_all_together_into_a_reset), the padding and margin are on the same line. It's hard to read.
=> Chore: Update reset code snippet

files/en-us/learn/css/building_blocks/values_tasks/index.html
This commit adds a missing "to" preposition in the first paragraph of the Task Three exercise.
In the first paragraph of the Task Three exercise there is a missing "to" preposition.
It says "In this task you need move...". It should say "In this task you need to move..."
=> Fix missing preposition in “CSS building blocks” task three

files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_typescript/index.html
Updates description to match example.
The description for a provided code example did not match. The example showcased how a typo would trigger a typecheck warning. 
=> Fix typo in “TypeScript support in Svelte” doc

.github/workflows/ping-other-repos.yml
For every push to the repo, the `.github/workflows/ping-other-repos.yml` file added in this change creates a GitHub `repository_dispatch` event to send a ping to the https://github.com/w3c/mdn-spec-links/ repo (where it triggers the build of the contents of that repo).
Along with https://github.com/w3c/mdn-spec-links/, other repos can be added to this later — any repos that want to have some action triggered each time a push to the BCD repo occurs.
https://github.com/marketplace/actions/repository-dispatch has docs on the GitHub Action this uses, and docs for the underlying API it uses are at https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
---
This is identical to the https://github.com/mdn/browser-compat-data/blob/main/.github/workflows/ping-other-repos. …
=> Add .github/workflows/ping-other-repos.yml

files/en-us/web/svg/attribute/events/index.html
This PR fixes the issue described in BCD at https://github.com/mdn/browser-compat-data/issues/11421.  The article's BCD entry was set incorrectly, and thus ended up rendering a blank compat table.
=> Update SVG event attributes page to point to correct BCD

files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
This fixes #6659 and fixes #6660
I:
- fixes some gremlins on the page (non-breaking spaces)
- removed a _however_ from the page (there are so many of them)
- corrected two sentences around the word _however_
=> Fix typos around 'however'

files/en-us/web/svg/index.html
They really serve nothing:
- Too old / Not maintained
- Uses Canvas API now (Google Docs / Maps)
- Does not provide any meaningful descriptions (or its source codes) to be given as examples
- Mixed feeling about the "SVG art gallery" link. Examples of SVG _images_?
- Turned into a paid service (JointJS)
None.
None.
=> Clean up external links from SVG landing page

files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.html
The sentence "_Pseudo-elements behave in a similar way, however they act as if you had added a whole new HTML element into the markup, rather than applying a class to existing elements._" is a **run-on sentence**.
Independent clauses cannot be joined by commas. This is called a **comma splice**, which is a type of **run-on sentence**.
=> fixed grammar

files/en-us/learn/javascript/asynchronous/promises/index.html
Just fixing a simple typo I saw. Changed from "a few more time" to "a few more times"
Without this fix, the sentence would be grammatically incorrect
=> Fix typo in "Promise Terminology Recap"

files/en-us/learn/javascript/asynchronous/introducing/index.html
Asynchronous functions aren't necessary going to be excused on a different thread.
Asynchronous functions aren't necessary going to be excused on a different thread. They get pushed off the stack so they won't block the whole thread. To push `async` function off the main thread, another agent is needed. Using `WebWorkers`, we can run `async` function on a separate thread. `WebWorkers` were not discussed in this article. Hence, mentioning this possibility in the **Conclusion** section could lead to confusion and incorrect understanding. 
This [Stack Overflow answer](https://stackoverflow.com/questions/49092985/difference-between-javascri …
=> Fix misleading statement in “Introducing asynchronous JavaScript”

files/en-us/learn/server-side/django/authentication/index.html
Django docs highly recommend using a custom user model when starting a new project. Mentioning about it here will help when learners start working on actual projects since changing to a custom user model mid-project can require significantly more effort.
https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project
https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project
=> “User authentication and permissions”﹕Mention custom user models

files/en-us/tools/storage_inspector/index.html
It seems that https://github.com/mdn/content/commit/9917877 (PR https://github.com/mdn/content/pull/618) inadvertently changed a URL that intentionally used an `http` scheme rather than `https`.
This changes it back to what it should be.
Fixes https://github.com/mdn/content/issues/6692
=> Restore a necessary http (non-https) URL

files/en-us/learn/html/introduction_to_html/the_head_metadata_in_html/index.html
Removed the "<kbd>Ctrl</kbd>" tag as the instruction doesn't add meaning to opening a page source code
The "<kbd>Ctrl</kbd>" that was added to the steps to follow when opening or viewing a page source code, doesn't perform the  task it was meant for, and removing it would stop the learner or reader from being confused.
=> Fix typo in /HTML/Introduction_to_HTML/The_head_metadata_in_HTML

files/en-us/learn/server-side/express_nodejs/mongoose/index.html
This updates the virtual method for getting author lifetime with the method in the [demo tutorial](https://github.com/mdn/express-locallibrary-tutorial/blob/master/models/author.js#L23), which is more robust (i.e. copes with missing date of birth or death.
Fixes #6759
=> Make Author lifetime string robust

files/en-us/learn/html/introduction_to_html/html_text_fundamentals/index.html
1) The notion of **semantics** isn't used in this lesson, which is concerned solely with **structure**. Besides, the preliminary gloss of semantics being about structure isn't true.
2) We can improve the phrasing a bit, as I hope I've done.
Fixes #6753
=> removed unnecessary wording, improved phrasing

files/en-us/learn/css/building_blocks/the_box_model/index.html
1) The MDN style guide calls for using the Oxford comma
2) The original opening consists of two independent clauses joined by a comma. This is a comma splice (or comma fault)
3) I tried to add some clarity, for example, by emphasizing the idea of SOME
=> improved mechanics

files/en-us/learn/css/building_blocks/the_box_model/index.html
The concept of a "**border box**" is a novel one. I have at least some understanding of what "**border box**" is as a **value** of "**box-sizing**" because I already understand the concepts of **properties** and **values**. But in the last sentence, "**By doing this you are telling the browser to take the border box as the area defined by any size you set.**" The concept of **border box** is reinvoked, this time _not_ as a value. So the meaning seems to have changed. If so, its meaning should be clarified. For example, does "**border box**" in the sentence equate to "**alternative CSS box**"? In any case, it's clear the idea is illustrated in the image above.
=> added clarity

files/en-us/learn/css/building_blocks/handling_different_text_directions/index.html
Fixes #7004
Heights on some EmbedGHLiveSample macros were much bigger than content. This reduces the whitespace.
=> Handling text_direction - fixing heights

files/en-us/learn/javascript/building_blocks/test_your_skills_colon__loops/index.html
Fixes #7009
As suggested in #7009, remove line referring to interactive editors. Editors don't exist, and removal is good fix as section works fine without it.
=> Test your skills: Loops - remove line about editors

files/en-us/learn/css/building_blocks/the_box_model/index.html
Fixes #6999
The issue correctly points out that the comment about the space occupied by the box repeats information that has been provided in the previous paragraphs. There were other issues with the sentence now fixed (e.g. only refers to width, not impact of padding on height etc) 
This also fixes heights of a couple of examples.
=> Clarify space taken up. Fix macro heights

files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
The main problem was the original used "**around**" instead of "**about**".
Words are **about** things. They are not around **things**.
=> improved diction (and commas)

pr-lint/src/index.js
In #7119, pr-lint didn't catch the useless pull request title as it was in the JS area, newly converted to Markdown.
This fixes this.
=> Adapt pr-lint action to handle md names too

files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
1) The original said that an image can embed an image file. But images just are image files. They can't embed themselves.
2) The original said we can see the extent of a file. That's confusing terminology. 
3) Other small fixes
=> various typographical improvements

.github/workflows/pr-review-companion.yml
If you look at https://github.com/mdn/content/actions/workflows/pr-review-companion.yml and you click into each one, you'll often see things like this:
The single thing that slows down the arrival of the preview URLs PR comment is the installation of `poetry`. 
After [much research](https://www.peterbe.com/plog/install-python-poetry-github-actions-faster) I've come up with a solution. 
Lots of context for the curious here: https://github.com/mdn/yari/pull/4328
=> cache $HOME/.local for faster poetry installation

files/en-us/learn/performance/css/index.html
There were 2 useless links in headings (the link was again in the first sentence right after)
=> Remove useless links in headings

files/en-us/learn/css/building_blocks/selectors/attribute_selectors/index.html
The description _"whose name is the value in square brackets"_ seems to be an unintentional duplication from previous table. i.e description of example `a[title] `
If not relevant to current example, can we please remove it?
=> Duplicated text from description can be removed.

files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.html
Since psudo-elements `::before` and `::after` _"inserts"_ content rather than _"matches"_ existing content, description changed accordingly.
=> Description of special pseudo elements refined.

files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.html
This fixes the flaw "Link points to the page it's already on"
=> Remove self-link on How the Web works

files/en-us/learn/css/css_layout/introduction/index.html
This fixes the following broken link flaw:
1. /en-US/docs/Learn/CSS/CSS_layout/Introduction 👀 line 710:15
Link points to the page it's already on
=> Remove self-link on introduction to CSS page

files/en-us/learn/css/building_blocks/the_box_model/index.html
Also, I've never seen a present participle or a gerund used to signify the name of a **categorial concept** before. It sounds odd to say "**margin collapsing**" as if it were such a concept. I may very well be wrong here, since my skills are with English and not with web development.
=> updates to the Box Model: margin collapsing

files/en-us/learn/common_questions/set_up_a_local_testing_server/index.html
Since Python 2 has been sunsetted on Jan 1st, 2020, we should rephrase the guide to focus on Python 3 examples first.
Also cleanup info about (and fix some links for) Python web frameworks. Since all of the frameworks mentioned provide a user guide on their websites, we do not need to describe how to install and run them here.
The guide was mentioning `SimpleHTTPServer` (Python 2) before `http.server` (Python 3). It also had some outdated info.
The instructions for installing and running Flask are extraneous for the purposes of this article.
=> Prefer Python 3 (http.server)

files/en-us/learn/javascript/first_steps/strings/index.html
URI fragment in link was incorrect. Updated link and changed link text to match the target section heading.
Link was broken, so it led to the top of the page rather than the desired section heading.
=> Fix broken fragment in “Handling text — strings in JavaScript”

files/en-us/learn/server-side/django/deployment/index.html
While following the Django deployment guide with the windows CMD I have encountered following issue:
```
>heroku version
heroku/7.56.1 win32-x64 node-v12.21.0
>heroku config:set DJANGO_DEBUG='False'
Setting DJANGO_DEBUG and restarting ⬢ homekeeper-backend... done, v13
DJANGO_DEBUG: 'False'
>heroku config:set DJANGO_DEBUG="False"
Setting DJANGO_DEBUG and restarting ⬢ homekeeper-backend... done, v14
DJANGO_DEBUG: False
```
With single quotes DJANGO_DEBUG was wrongly set to `'False'` and because of that, in the settings.py: `DEBUG = "'False'" != "False"` => `DEBUG = True` .
Not sure if this parsing behavior is …
=> Change DJANGO_DEBUG='False" to double quotes

files/en-us/learn/html/introduction_to_html/getting_started/index.html
This change increases the height of the “This is my page” embedded live sample in the “Getting started with HTML” article.
Otherwise, without this change, when the reader pushes the **Show solution** button, the **Editable code** area appears to be replaced by a large image.  However, in fact, the **Editable code** area isn’t replaced by the image; instead the image gets placed vertically before the **Editable code** area.  And because the height of the iframe for the embedded live sample is too small, the **Editable code** area seems to disappear. In fact, though, the **Editable code** area is still there, but the reader needs to scroll the iframe to view it — which is not immediately obvious to most readers.
So this change increases the height of the iframe for the embedded live sample …
=> Increase live-output height of “Getting started with HTML” example

files/en-us/learn/javascript/first_steps/math/index.html
I corrected the definition of integers on line 49...
The previous definition was wrong as it said that "Integers are whole numbers" and this statement was totally wrong because whole numbers are a set of numbers that include all positive numbers and 0, therefore whole numbers can't be negative but integers can be negative
Every whole number is an integer but every integer is not a whole number
=> Fix the definition of integers in “Basic math in JavaScript” doc

files/en-us/learn/server-side/django/introduction/index.html
In Markdown we don’t have the ability to make parts of code blocks bold (or italic either). So to help make the “Django introduction” article Markdown-ready, the existing *“The line in bold [in the code block below] shows”* statement needs to be changed to make sense without requiring boldfacing of the relevant line in the code block. The fix that’s easiest and clearest is to just replace the *“The line in bold”* reference by copying the relevant line verbatim into the paragraph. Fixes https://github.com/mdn/content/issues/7958.
=> Fix reference in bold in <pre> in “Django introduction” doc

files/en-us/web/svg/element/view/example.svg, files/en-us/web/svg/element/view/index.html
No issue.
The SVG file was a base64 encoded data URI, I don't think this is well suited for examples. In my opinion the new example reflects a more common use case (choosing a specific detailed view in an external file).
Link to the current example: 
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/view#example
=> Improve SVG `<view>` example

.github/workflows/pr-check_redirects.yml, .github/workflows/pr-test.yml, .github/workflows/preview.yml
Fixes #8014
Now, the cache keys for caching `node_modules` is unique per each `.yml` file so you shouldn't be getting that error.
=> Make GitHub Action cache keys for node_modules unique per workflow

.github/dependabot.yml, .github/workflows/pr-lint.yml, pr-lint/package.json, pr-lint/yarn.lock
The Dependabot checks weren't configured for `pr-lint/package.json`.
We don't need to run a specific old version of Node either.
=> update CI for pr-lint script

.github/workflows/pr-test.yml
See https://github.community/t/how-come-the-actions-cache-is-failing-so-much-often/196279/3
The objective is to speed up PR CI by making sure that the cache is more often hot for PRs. PRs, won't be able to access the cache (e.g. `node_modules`) unless it was stored when built on the default branch (`main`).
=> run pr-test CI on main branch too

files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.html
The existing “Order in which component files are parsed” section of the “How the Web works” article had a confused description that didn’t align with how things actually work. This change corrects it.
Fixes https://github.com/mdn/content/issues/8096
=> Clarify “How the Web works” section describing parse order

files/en-us/web/svg/tutorial/clipping_and_masking/index.html
N/A
"It is therefore little surprise, that (...)" is not grammatically correct. I figured it's meant to say "(...) a little surprising, that (...)".  
It's beyond me to try to interpret the intended meaning besides a small grammatical error, but it seems to me that it's not surprising for "One of the most powerful tools in a web developer's toolbox" to be put into SVG. This PR makes it grammatically correct, but someone might want to check if the sentence itself makes sense.
=> Fixed small grammatical error on the Clipping and Masking page

files/en-us/learn/performance/multimedia/index.html
In this PR, you'll find two small enhancements to the `learn/performance/multimedia` reference:
- add a needed (empty) alt attribute in one code example
- add `<picture>` alongside `<img>` element
Cheers,
Jb
=> Code example fix and a small enhancement on `learn/performance/multimedia`

files/en-us/learn/javascript/building_blocks/conditionals/index.html
None that I know of
To have consistent code style around all OR operators
Not really, very minor change
=> Fix lack of one space after an OR operator

files/en-us/web/svg/element/symbol/index.html
No issue.
The example still uses the deprecated `xlink:href` attribute instead of the standard `href`.
This can be useful for backwards compatibility but I don't think it should be in the example.
We could add a note about this but I don't think it's necessary as there is already one on the `<use>` page.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use#attr-xlink
=> Improved SVG <symbol> example

files/en-us/web/svg/tutorial/basic_shapes/index.html
When a user copies the code of Line element and runs in local device, it shows nothing. It is because there is no stroke attribute associated. So, here I have proposed change for line element code.
>
>If user directly copies the content of line element then it will not show any output in their local device. So, I have attached stroke attribute in line element.
=> Line element better code for user ease.

files/en-us/learn/javascript/asynchronous/promises/index.html
- remove `seosummary` and `standard-table` class
- add semicolon after function expression
- fixes #8417
=> Remove semicolon after function declaration

files/en-us/web/svg/tutorial/getting_started/index.html
From getting started guide.
It has nothing to do here in a getting started guide.
Arguably removing `version="1.1"` should be done too, as it is also deprecated in svg v2.
=> Remove deprecated baseProfile svg attribute

files/en-us/web/svg/attribute/x/index.html, files/en-us/web/svg/attribute/y/index.html
None
The documentation for [symbol](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol) and [cursor](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/cursor) SVG elements correctly says that these elements allow `x` and `y` attributes. However, the section "You can use this attribute with the following SVG elements" for these attributes misses these elements.
The PR adds `cursor` and `symbol` elements into the list of supported elements in the documentation for `x` and `y` attributes.
=> SVG: x and y attributes can be set for <cursor> and <symbol>

files/en-us/tools/debugger/how_to/pretty-print_a_minified_file/index.html
Fixes #3222
Can't pprint inline JS on FF 91 on Win 10 either.  Possibly due to [https://bugzilla.mozilla.org/show_bug.cgi?id=1010150](Can't pretty-print / deobfuscate / beautify inline scripts)
This bug needs-triage. Feel free to put on hold until then.
=> Fixes #3222

files/en-us/learn/javascript/objects/inheritance/index.html
Using “attributes” isn’t wrong, but for consistency with the terminology in the rest of the article — and because this is an introductory tutorial in the Learn tree, for beginners — it’s better to just stick with “properties” here.
Fixes https://github.com/mdn/content/issues/8445
=> Use “properties”, not “attributes” in “Inheritance in JavaScript”

files/en-us/web/svg/attribute/by/index.html, files/en-us/web/svg/attribute/preserveaspectratio/index.html, files/en-us/web/svg/attribute/viewbox/index.html
None
There is `</li>` missed in the docs for `<by>`. Also, I've dropped `.` from 2 lists for consistency with other SVG attributes docs.
=> SVG <by>: add missed </li>

files/jsondata/GroupData.json
For #8381 I created a "Web Share API" doc. This API includes `navigator.canShare()` and `navigator.share()` methods.
This PR updates the groupdata to add a new sidebar menu for "Web Share API" with those two methods. I had expected to add this new API to both the methods.
Before I do ... (or merge this) ...  the two methods currently link to "{{APIRef("HTML DOM")}}". Is it the "right thing" to do to create this sidebar and apply it to those methods, or can I somehow have both sidebars?
=> Add Web Share API to GroupData.json [ADVICE FIRST BEFORE MERGE!]

files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.html
The information in this section about browsers making repeat DNS lookups for absolute URLs is plain wrong, and the other reason — “makes reading code much easier” — doesn’t seem like a super-compelling reason.
The choice between using relative URLs and absolute URLs is something depends on what kind of content it is and what the anticipation is for reusing/moving the content elsewhere. So a blanket “Use relative links wherever possible” recommendation doesn’t really make sense anyway. Fixes https://github.com/mdn/content/issues/8517.
=> Drop “Use relative links” section from “Creating hyperlinks” doc

files/en-us/learn/server-side/django/admin_site/index.html, files/en-us/learn/server-side/django/authentication/index.html, files/en-us/learn/server-side/django/deployment/index.html, files/en-us/learn/server-side/django/development_environment/index.html, files/en-us/learn/server-side/django/django_assessment_blog/index.html, files/en-us/learn/server-side/django/forms/index.html, files/en-us/learn/server-side/django/generic_views/index.html, files/en-us/learn/server-side/django/home_page/index.html, files/en-us/learn/server-side/django/introduction/index.html, files/en-us/learn/server-side/django/models/index.html, files/en-us/learn/server-side/django/sessions/index.html, files/en-us/learn/server-side/django/skeleton_website/index.html, files/en-us/learn/server-side/django/testing/index.html, files/en-us/learn/server-side/django/tutorial_local_library_website/index.html, files/en-us/learn/server-side/django/web_application_security/index.html, files/en-us/learn/server-side/express_nodejs/deployment/index.html, files/en-us/learn/server-side/express_nodejs/development_environment/index.html, files/en-us/learn/server-side/express_nodejs/displaying_data/index.html, files/en-us/learn/server-side/express_nodejs/forms/index.html, files/en-us/learn/server-side/express_nodejs/introduction/index.html, files/en-us/learn/server-side/express_nodejs/mongoose/index.html, files/en-us/learn/server-side/express_nodejs/routes/index.html, files/en-us/learn/server-side/express_nodejs/skeleton_website/index.html, files/en-us/learn/server-side/express_nodejs/tutorial_local_library_website/index.html, files/en-us/learn/server-side/first_steps/client-server_overview/index.html, files/en-us/learn/server-side/first_steps/introduction/index.html, files/en-us/learn/server-side/first_steps/web_frameworks/index.html, files/en-us/learn/server-side/first_steps/website_security/index.html
This removes the table classes from learn boxes, at the top of learn pages: `learn-box standard-table`. The rendering remains unchanged, as shown below.
@wbamberg @teoli2003 This is just a general tidy, prior to doing proper markdown conversion. 
Do you have an opinion for the "right way" to have these in markdown? My leaning is towards either leaving "as is" or a definition list like this:
Do you have an opinion? Who else do we need "buy in" from?
=> Markdown Learn/Server-Side: Table - strip class (standard-table and learn-table)

files/en-us/learn/server-side/configuring_server_mime_types/index.html, files/en-us/learn/server-side/django/deployment/index.html, files/en-us/learn/server-side/django/development_environment/index.html, files/en-us/learn/server-side/django/generic_views/index.html, files/en-us/learn/server-side/django/home_page/index.html, files/en-us/learn/server-side/django/skeleton_website/index.html, files/en-us/learn/server-side/django/testing/index.html, files/en-us/learn/server-side/express_nodejs/deployment/index.html, files/en-us/learn/server-side/express_nodejs/development_environment/index.html, files/en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page/index.html, files/en-us/learn/server-side/express_nodejs/displaying_data/locallibrary_base_template/index.html, files/en-us/learn/server-side/express_nodejs/displaying_data/template_primer/index.html, files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.html, files/en-us/learn/server-side/express_nodejs/forms/create_book_form/index.html, files/en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form/index.html, files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.html, files/en-us/learn/server-side/express_nodejs/forms/delete_author_form/index.html, files/en-us/learn/server-side/express_nodejs/forms/update_book_form/index.html, files/en-us/learn/server-side/express_nodejs/introduction/index.html, files/en-us/learn/server-side/express_nodejs/mongoose/index.html, files/en-us/learn/server-side/express_nodejs/routes/index.html, files/en-us/learn/server-side/express_nodejs/skeleton_website/index.html, files/en-us/learn/server-side/first_steps/client-server_overview/index.html
Fixes #8561 
This adds `<pre class="brush: plain">` to all empty pre blocks in Learn/server side. This adds the copy content icon to rendered content, which is not present otherwise. I'm also hoping it simplifies markdown conversion :-)
=> Add brush: plain to pre blocks in server side

.github/CODEOWNERS
Removes @peterbe from CODEOWNERS, replacing with @escattone. I also updated the `AUTOMERGE_TOKEN` to use a new personal access token owned by @escattone.
=> remove peterbe from CODEOWNERS

files/jsondata/InterfaceData.json
URL's mixins are no more (if ever) documented on MDN.
This deletes their remnant in InterfaceData.json used for the sidebar creation.
This will clean about 40 MacroPagesError flaws.
(Note: I know that for the moment this InterfaceData.json is not yet in use, but this is not critical, I just want to get this in before I forget about it)
=> Remove 2 non-documented mixins in InterfaceData.json

files/jsondata/InterfaceData.json
This removes the remaining mixins from the current `InterfaceData.json` file.
This PR has two goals:
- it actually fixes about 90 flaws
- it will allow us to see if there are regressions when using a generated `InterfaceData.json `in the future. As the newly generated file will not remove flaws, it will be easy to check if there are new flaws introduced by it. (As we just have to check if the numbers are going up)
=> Remove remaining mixins from InterfaceData

files/en-us/learn/css/css_layout/multiple-column_layout/index.html
The` </div> ` of hidden block was inserted before the following code snippet
```
<pre class="brush: css">.container {
column-width: 200px;
}
```
So currently this css code snippet is repeatedly appearing.
I have moved the ` </div> ` below this code snippet to hide the repetition.
=> Closing div tag of hidden div block relocated.

files/en-us/web/svg/attribute/color/index.html, files/en-us/web/svg/attribute/cx/index.html, files/en-us/web/svg/attribute/cy/index.html, files/en-us/web/svg/attribute/d/index.html, files/en-us/web/svg/attribute/dx/index.html, files/en-us/web/svg/attribute/dy/index.html, files/en-us/web/svg/attribute/fill-rule/index.html, files/en-us/web/svg/attribute/points/index.html, files/en-us/web/svg/attribute/preserveaspectratio/index.html, files/en-us/web/svg/attribute/stroke-linecap/index.html, files/en-us/web/svg/attribute/stroke-linejoin/index.html, files/en-us/web/svg/attribute/transform/index.html, files/en-us/web/svg/attribute/x/index.html, files/en-us/web/svg/attribute/x1/index.html, files/en-us/web/svg/attribute/x2/index.html, files/en-us/web/svg/attribute/y/index.html, files/en-us/web/svg/attribute/y1/index.html, files/en-us/web/svg/attribute/y2/index.html, files/en-us/web/svg/tutorial/texts/index.html
Part of https://github.com/mdn/content/issues/8969.
This PR removes `<div class="hidden">` from the SVG docs, and transfers "hidden" to the code blocks they contained.
In a couple of pages the hidden `<div>` also wrapped a heading that was used by a live sample, so I adjusted things a bit there.
=> [Markdown] [Web/SVG] Remove hidden DIVs from SVG docs

files/en-us/web/svg/attribute/in/index.html, files/en-us/web/svg/attribute/transform-origin/index.html, files/en-us/web/svg/tutorial/gradients/index.html
Part of https://github.com/mdn/content/issues/8969.
This fixes up the places in the SVG docs where a heading ID is different from the generated heading ID, and a live sample uses that ID. This will break in Markdown because in Markdown all heading IDs are always generated.
=> [Markdown] [Web/SVG] Fix live sample ID arguments for SVG

files/en-us/web/svg/element/filter/index.md
1. Remove screenshot image of live example
2. increase height to remove vertical scrolling
[99.3% global support of svg filter](https://caniuse.com/svg-filters)
=> Remove Image in Example of <filter> svg ref

files/en-us/web/svg/tutorial/basic_shapes/index.md
The H2 wasn't helping anything here since it matched the H1, and then all the shapes themselves were H3s, thus excluded from the sidebar table of contents.  This upgrades them to H2s for inclusion there.
Because the TOC looked like this:
From that, I couldn't get a quick list of shapes at a glance.
n/a
n/a
This PR…
=> Cut H2 dupe of H1, make TOC more useful

files/en-us/web/svg/element/index.md
There is no `unknown` element in the literal sense. But any unknown SVG elements can be rendered which is not explicit in the list. Thanks to @fabricereix for reporting. 
Low hanging :mango:
[W3 SVG uknown element](https://www.w3.org/TR/SVG2/struct.html#UnknownElement)
Fixes #10584
=> Deletes literal `unknown`, adds note

.github/dependabot.yml, .github/workflows/system-file-changes.yml, .gitignore
The pr-lint feature was removed in https://github.com/mdn/content/pull/9952. It seems that dependabot is still running for this folder (https://github.com/mdn/content/pull/9417) and so this PR removes the remaining occurrences of "pr-lint".
=> Remove rest of pr-lint

.github/workflows/new-issues.yml
Adding a workflow to add the `needs-triage` label automatically to new issues
Followed https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
=> Automating needs triage for new issues

files/jsondata/InterfaceData.json
https://github.com/w3c/webref/ automatically maintains the list of IDL interfaces defined in browser specifications.
InterfaceData.json can be generated from this data; before making my [initial script](https://gist.github.com/dontcallmedom/4ce7183bd1ac9d6bf79ae11da12f1898) robust enough for automatic updates to this repo, I'm submitting the data that can be extracted from there to see if this is indeed an improvement over the currently manually maintained file.
If it emerges that this is good, I'll complete this pull request with a github action to update the data file on a weekly basis.
Because a JSON diff can be difficult to review, I'm also embedding below a higher level summary (generated via [jsodiff](https://github.com/dontcallmedom/jsodiff)):
```diff
+ "ANGLE_instanced_arrays": …
```
=> Update InterfaceData based on webref

files/en-us/web/svg/element/defs/index.md
Replace deprecated `xlink:href` by `href`
as described in https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href, `href` should now be used instead.
=> Replace deprecated xlink:href by href

files/en-us/web/svg/element/defs/index.md
The xlink namespace is not used anymore in the document
=> Remove unnecessary namespace declaration

files/jsondata/GroupData.json
Fixes #11498
This makes the HTML Dom API overview link from the main [Web API](https://developer.mozilla.org/en-US/docs/Web/API) page.
=> Add HTML DOM API to web apis

files/en-us/web/svg/tutorial/getting_started/index.md
Fixes https://github.com/mdn/content/issues/12756
The end tag for the `object` element is required in `text/html` documents; self-closing tags don’t work in `text/html`.
=> Add missing </object> end tag in SVG “Getting started” example

files/jsondata/GroupData.json
Add `DOMRect` and `DOMRectReadOnly` interfaces to _Geometry Interfaces_ API sidebar.
They are missing from the sidebar.
=> Add DOMRect to Geometry Interfaces group

.github/workflows/markdown-lint.yml, .github/workflows/pr-check_redirects.yml, .github/workflows/pr-test.yml, .github/workflows/preview.yml
Unpin the setup-node version to the major v2, so it stays up-to-date without dependabot noise. Swap the custom caching with the now built-in support in setup-node in v2
=> ci: use built-in setup-node caching

.gitattributes
This change causes GitHub to recognize that the repo sources are currently 97.1% Markdown and 2.9% HTML.
Otherwise, without this change, the GitHub UI incorrectly shows the repo sources as being 100% HTML.
See also https://joshuatz.com/posts/2019/how-to-get-github-to-recognize-a-pure-markdown-repo/#solution-start but note that the syntax used there doesn’t match what’s documented in https://github.com/github/linguist/blob/master/docs/overrides.md#detectable. Specifically, the documentation indicates it’s sufficient to just include the `linguist-detectable` attribute; appending `=true` to it is unnecessary.
And see https://github.com/sideshowbarker/content for what the GitHub UI will show after this change is merged:
=> Make GitHub recognize the repo sources are largely Markdown

files/en-us/web/svg/attribute/text-anchor/index.md
Earlier the link of inline-size on text-anchor page is redirecting to a page which does not having any doc.
The issue is with the attribute link of the inline-size.
Changes:
Earlier: In the code of index.md of text-anchor
{{SVGAttr("inline-size")}}
Now   : 
{{cssxref("inline-size")}}
After this change the page is now redirecting to the right link of inline-size.
On the Image we can see the change on hovering on the inline-size, is now giving the right the link.
As it was my first contribution in the mdn docs, it gives me zest to contribute more in open source projects.
Thank You
=> Updated the SVGAttr with CSSRef to fix the link which is not working

files/en-us/web/svg/element/symbol/index.md
Fixes https://github.com/mdn/content/issues/14165. Spec references:
- https://svgwg.org/svg2-draft/struct.html#SymbolElementRefXAttribute
- https://svgwg.org/svg2-draft/struct.html#SymbolElementRefYAttribute
=> Fix the default value for SVG <symbol> refX/refY

.github/labeler.yml
This eliminates the auto-assignment of deeply-nested `Content:Learn:*` labels.
The content team thinks the existing `Content:Learn` sublabels are too finely sliced (and incomplete).
=> Drop a couple auto-assigned labels

files/en-us/web/svg/element/femergenode/index.md
Link to SVG Core Attributes page went to non-existent anchor, so I changed it to the SVG Core Attributes page
This PR…
-->
=> Fixed Internal Link to SVG Core Attributes

files/jsondata/SpecData.json
ARIA was pointing to ARIA 1.1 which has been heavily changed. 1.3, while still in ED, has a lot of features implemented and is the defacto standard.
=> Updated specName: ARIA 1.3

.github/ISSUE_TEMPLATE/page-report.yml
This creates a form-based template with required fields for prefilling via Yari.
To improve response rates on new issues and to divert issues before they've opened.
=> Add a new form-based page report template

files/en-us/web/svg/attribute/x1/index.md, files/en-us/web/svg/attribute/x2/index.md, files/en-us/web/svg/attribute/y1/index.md, files/en-us/web/svg/attribute/y2/index.md
Fixes https://github.com/mdn/content/issues/14954
The spec allows <length-percentage> | <number> for all these.
Spec reference: https://svgwg.org/svg2-draft/shapes.html#LineElementX1Attribute
=> Align the allowed values for SVG x1, x2, y1, y2 with spec

files/en-us/web/svg/element/circle/index.md
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r#circle has the correct allowed values per the requirements in the spec at https://svgwg.org/svg2-draft/geometry.html#R — so this change both aligns with the spec and makes it internally consistent in MDN. Fixes https://github.com/mdn/content/issues/14957.
=> Make SVG <circle> doc have correct allowed value for “r” attribute

files/en-us/web/svg/attribute/fr/index.md
Fixed a bug that caused the first and second example on https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fr to use the same image by changing the label on both headers and their respective EmbedLiveSample funtions. Also, changed the sizing of the second example's svg to make it fit within the white rectangle.
This fix makes it so that the example HTML displayed in the web page coincides with the image shown, making it less confusing for readers and learners.
This PR rewrote some lines of code on the content/files/en-us/web/svg/attribute/fr/index.md file.
Fixes #15058
=> Fix Issue #15058

meta/content/en/governance/issues/triage.md
This adds a draft issue triage process for mdn/content.
I think one trick is discussing issues in enough detail to make good decisions, but still get through enough in 30 minutes. I'm especially worried that including a bit about "write an outline of how to fix it" will take too long but it does seem like it would be very useful to include it.
How many is "enough"? We average about 50 issues/week (and have a big backlog). But I hope that some number of incoming issues will just get fixed (or closed) anyway without going through triage.
=> Add triage process doc

files/en-us/web/svg/tutorial/paths/index.md
Fixes the following incorrect assertion regarding using `S` in an SVG Path to describe a cubic Bézier: "In this case the result is the same as what the Q command would have produced with the same parameters."
It's wrong on the internet.
In general a cubic Bézier can be reduced to a quadratic only if the two off-curve control points are coincident. The `S` command does not produce this.
More concretely, you can see for yourself with the following SVG:
```
<svg width="190" height="160" xmlns="http://www.w3.org/2000/svg">
<path d="M 10 80 S 150 150, 180 80" stroke="black" fill="transparent"/>
<path d="M 10 80 Q 150 150, 180 80" stroke="red" fill="transparent"/>
</svg>
```
None
=> Fix assertion about abbreviated S command

files/en-us/web/svg/tutorial/paths/index.md
This dictionary.com https://www.dictionary.com/browse/string entry lists strung as the preferred past tense of the verb to string.
I was pulled out the the text briefly while reading the word stringed.  Reviewing the writing style guidelines it appears this should be strung as the past tense.
https://www.dictionary.com/browse/string
This PR…
=> Past tense of to string is strung

files/jsondata/GroupData.json
`CSSMatrix` and `Point` don't exist anymore (they are aliases or long removed).
We don't want them in the sidebar (and they create 2 flaws on each article about Geometry API.
=> Update GroupData.json for Geometry Interfaces sidebar

files/jsondata/GroupData.json
This cleans the sidebars from numerous small APIs:
- change redirected page to the right link
- remove deleted dictionaries
- remove deleted `onXYZ` properties.
Cleaner sidebars and fewer flaws.
=> Fix sidebars for API from R to Z

files/jsondata/GroupData.json
Fixes all sidebars for API from G to P (except HTML DOM that will have its own PR as it affects > 1000 pages):
- Removed `onXYZ` deleted during the event project
- Fix a few renamed pages
This will remove flaws, make the renamed pages re-appear in the sidebar, and deleted a few red links that will be red forever.
=> Fix sidebars by updating GroupData.json (letters G-P)

files/jsondata/GroupData.json
There was a typo in (`MediaKeySessionEvent` -> `MediaKeyMessageEvent`, per both the spec and was is documented on MDN).
And a red link to `onencrypted` that I transformed into a red link to `HTMLMediaElement: encrypted`.
=> Fix-sidebar-for-EME

files/jsondata/GroupData.json
Remove the XDomain group from GroupData.json.
This is not used anymore (for a long time) on MDN. Time to clean this up.
=> Remove XDomain group

files/jsondata/GroupData.json
`IDBEnvironment` and `IDBVersionChangeRequest` are:
- non-standard
- not implemented (nothing in bcd…)
- not documented.
This PR removes them from the IndexedDB sidebar.
=> Fix IndexedDB sidebar

files/en-us/web/svg/attribute/type/index.md
This is against our convention, is unclickable, and leads to flaws.
=> Remove links from headings in SVG's attribute type

.github/workflows/json-lint.yml, .github/workflows/markdown-lint.yml, .github/workflows/pr-check_redirects.yml, .github/workflows/pr-test.yml, .github/workflows/preview.yml
This PR updates all workflows to use NodeJS v16 rather than v12.  Required to land #15866.
=> Use NodeJS v16 for workflows

files/jsondata/GroupData.json
`ChromeWorker` was an old attempt, long forgotten. Let's remove it from the sidebar (red link anyway)
=> Remove ChromeWorker from GroupData

files/jsondata/GroupData.json
It is not documented, not in the relevant spec, and no mention found elsewhere. Let's remove this red link from the sidebars.
=> Remove non-existent ScreenLuminance from sidebars

files/en-us/web/svg/attribute/d/index.md
We erroneously used Bézier in the slug for Bezier_curve. This was fixed long ago, but we forgot these occurrences.
This PR fixed this.
=> Fix Bézier -> Bezier

files/jsondata/GroupData.json
We don't have these pages anymore. Should not be in a sidebar.
=> Remove mention of .oncontentdelete in GroupData

files/jsondata/GroupData.json
As it was not implemented in any browsers, we removed the docs for WEBGL_compressed_texture_atc.
We also need to remove it from GroupData.json, or we have a useless red link in each WebGL sidebar.
This PR fixes it.
=> Remove mention of WEBGL_compressed_texture_atc

files/jsondata/GroupData.json
We deleted this page yesterday (not implemented in any release browsers for almost a decade).
We also need to remove it from the sidebars.
=> Remove Navigator.battery from sidebars

.github/issue-regex-labeler.yml
This change un-breaks our _“Label issues by MDN URL or other regex match in issue description”_ GitHub Action — which has been broken since May 14, when we upgraded our github/issue-labeler version from v2.0 to v4.1 in https://github.com/mdn/content/commit/fcaab4f.
Otherwise, without this change, when github/issue-labeler v4.1+ see slashes in the paths/slugs in our `issue-regex-labeler.yml` — for example, `'/docs/Web/Accessibility'` — the slashes don’t get parsed as literal slashes but instead are considered to be delimiters of the start and end of regex patterns. And that causes a failure with:
> Error: SyntaxError: Invalid flags supplied to RegExp constructor 'Accessibility'
=> Actions: Escape slashes in issue-regex-labeler.yml

files/en-us/web/svg/attribute/xlink_colon_href/index.md
Fixes https://github.com/mdn/content/issues/16300 • Related BCD issue: https://github.com/mdn/browser-compat-data/pull/16386
=> Add browser-compat key and compat table to SVG xlink:href doc

files/en-us/web/svg/attribute/xlink_colon_href/index.md
Added a note that `xlink:href` may be included in addition to `href` to support older browsers.
We recently tried removing `xlink:href` from an svg sprite we use for our site, and found that it broke the sprite for users on Safari < 12.1, as specified by the browser support table. Looking at our analytics, this only comprises a portion of a single percent of our users - but this is still over a thousand users a week. Therefore, it seems worthwhile to note that both attributes may be included, which allows rendering on Safari < 12.1, but also future-proofs against browsers dropping support for `xlink:href`.
Note that this is supported in the W3 SVG2 spec [here](https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs): 
> When the ‘href’ attribute is present in both the XLink namespace and …
=> Noting xlink:href fallback option to support older browsers

files/en-us/web/svg/attribute/href/index.md
Added a note that `xlink:href` may be included in addition to `href` to support older browsers.
We recently tried removing `xlink:href` from an svg sprite we use for our site, and found that it broke the sprite for users on Safari < 12.1, as specified by the browser support table. Looking at our analytics, this only comprises a portion of a single percent of our users - but this is still over a thousand users a week. Therefore, it seems worthwhile to note that both attributes may be included, which allows rendering on Safari < 12.1, but also future-proofs against browsers dropping support for `xlink:href`.
Note that this is supported in the W3 SVG2 spec [here](https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs): 
> When the ‘href’ attribute is present in both the XLink namespace and …
=> Noting fallback technique for xlink:href to support older browsers

.github/workflows/pr-check_scripts.yml, package.json, yarn.lock
This reverts commit 691d6023f91180eb955b3c10ee24ee8b66ee3839, **and** introduces a "Check scripts" workflow that runs all `package.json` scripts when dependencies change.
1. This downgrades yari to fix the failing scripts (due to a TypeScript migration in yari) as a workaround.
2. This prevents future yari bumps from being merged if it breaks any of the scripts.
=> Downgrade @mdn/yari from 1.1.14 to 1.1.26 and check scripts when dependencies change

files/jsondata/GroupData.json
This is the last part of #15468
It add a missing property to the sidebar for Prioritized Task Scheduling (the global property used to access it - originally wasn't sure where it would live in the docs tree).
=> Add window.scheduler to Prioritized Task API sidebar

files/en-us/web/svg/attribute/x/index.md
I altered the grammar of some of the paragraphs on this page so they would read better.
Some of the paragraphs on this page did not read very well to me.
I made similar changes to the `y` SVG Attribute page in #17276
=> Nit: Some grammatical changes to the prose

files/en-us/web/svg/namespaces_crash_course/index.md
Fixes https://github.com/mdn/content/issues/17580
`hasAttribute` was (I think) first implemented browsers as part of DOM Level 1 — even though it was not part of the DOM Level 1 spec. It didn’t get specified formally until DOM Level 2.
Given all that, it’s not inaccurate to list it in the table in the “Namespaces crash course” page as a DOM Level 1 element — while linking to the DOM Level 2 spec for its definition.
So that’s what this change does.
=> Fix a link in “Namespaces crash course”

files/en-us/web/svg/attribute/side/index.md, files/en-us/web/svg/attribute/xml_colon_lang/index.md, files/en-us/web/svg/element/cursor/index.md, files/en-us/web/svg/element/filter/index.md, files/en-us/web/svg/element/font-face-format/index.md, files/en-us/web/svg/element/font-face-name/index.md, files/en-us/web/svg/element/font-face/index.md, files/en-us/web/svg/element/font/index.md, files/en-us/web/svg/element/glyph/index.md, files/en-us/web/svg/element/glyphref/index.md, files/en-us/web/svg/element/hkern/index.md, files/en-us/web/svg/element/missing-glyph/index.md, files/en-us/web/svg/element/view/index.md, files/en-us/web/svg/element/vkern/index.md
Same as https://github.com/mdn/content/pull/19185, but for HTTP pages.
The PR updates tags, headers, and inline badges as per current BCD v5.1.10.
:warning: This completes SVG updates
***
**Note:** We are simply synchronizing it with BCD. If you have objection with any compatibility status then raise an issue or PR in https://github.com/mdn/browser-compat-data repo. After BCD gets updated it'll be updated in HTML content automatically.
=> SVG: update BCD Info

package.json
Current configuration says the repo supports node version `>=12.0.0`. But now none of the dependency supports node version below `12.13.0`.
If a contributor, with older node installed, tries to run the scripts may face errors.
Here are the current engine requirements using [ls-engines](https://www.npmjs.com/package/ls-engines) tool:
```bash
> ls-engines
`node_modules` found; loading tree from disk...
┌────────┬─────────────────────────────────────────────────────────────────┐
│ engine │ Currently available latest release of each valid major version: │
├────────┼─────────────────────────────────────────────────────────────────┤
│ node   │ v18.8.0, v17.9.1, v16.17.0                                      │
└────────┴─────────────────────────────────────────────────────────────────┘ …
```
=> Bump engine requirement from 12.0.0 to 16.0.0

files/en-us/web/svg/attribute/href/index.md
The first example of `href` and `xlink:href` being used together was missing a quote from one of the attribute values, so I tacked one on.
Improve the readability for users and maintain the MDN reputation for quality docs. Beyond that, typos **seriously** trigger my OCD, so I'm also fixing this with slightly self-serving motives 😅
N/A
N/A
=> fix: typo in svg/attribute/href/index.md

files/en-us/web/svg/attribute/presentation/index.md
Fixes #22227
A typo - "nonezero" to "nonzero".
=> SVG presentation attribute - fix typo nonezero

files/en-us/web/svg/attribute/stroke-dasharray/index.md
Add "space at start" example for `stroke-dasharray`.
Notice: the fr translation is available at https://github.com/mdn/translated-content/pull/9945
It is not clear that we can start our "pattern" using a space. Doing that clarify that this is possible and show a simple way to achieve our result.
N/A
I did not open an issue for this.
@cw118
=> stroke-dasharray: add "gap at start" example

files/en-us/web/svg/tutorial/paths/index.md
Added alt text for five images on the SVG Paths tutorial page for Issue #21616 
Alt text is needed for every image on the site for accessibility.
For Issue #21616, related Pull Request of #22021.
=> Add alt text to SVG Tutorial Paths page for Issue #21616

files/en-us/web/svg/index.md
Make Scalable Vector Graphics take the singular verb _is_.
I would argue that the noun Scalable Vector Graphics is singular in meaning. So it should take the singular verb, is.
In addition, there are other mentionings of the noun Scalable Vector Graphics in the docs, all of which take a singular verb. For example, the introductory sentence in the [SVG Tutorial](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial).
=>  “Scalable Vector Graphics (SVG) *are* an XML-based markup language” (not “is an XML-based markup language”)

files/en-us/web/svg/attribute/viewbox/index.md
Currently there is needless overflow as demonstrated by the scrollbar:
This change stops the overflow from happening and so the scrollbar does not needlessly appear.
Tested fix in Firefox and Chrome.
=> Fix: Prevents needless overflow

files/en-us/web/svg/tutorial/gradients/index.md
* Link to the `defs` SVG element reference page at the beginning of the document.
* Wrap the remaining  defs with `<defs>`.
* Revise section by removing the first personal pronoun and using the correct ids from the code snippet.
* Fix typo: voila -> voilà
* Wrap code values in ``; for example `"pad"`.
=> Revise svg gradients tutorial

files/en-us/web/webdriver/index.md
> driver.find_element_by_name("q").send_keys("cheese" + Keys.RETURN) 
> driver.find_element(By.NAME, "q").send_keys("cheese" + Keys.RETURN)
Works well for me and doesn't result in the above error.
Thanks.
One of the functions being used I believe is now deprecated and results in an error back.
The code I'm purposing doesn't result in an error.
Please execute the new code and let me know if you get an error back, thanks.
=> updated method find_element_by_name

files/en-us/web/svg/tutorial/filter_effects/index.md
* Remove comma between subject and main verb (Between the filter tags, goes).
* Use the semi-colon to separate list items that have nested commas. For example: Sets `x` to 12, which is number; shifts `x`; and then displays the result.
=> Make minor punctuation fixes

files/en-us/web/svg/attribute/xml_colon_space/index.md
While the existing example is not wrong, it does not in any way illustrate the effect of using the xml:space attribute. The changes added some additional spaces to show that the extra spaces are processed differently depending on the value given to the attribute.
=> Made the example useful

files/en-us/web/svg/element/femergenode/index.md
The extremely old: `/en-US/docs/DOM/` is now `/en-US/docs/Web/API`
=> Fix link to interface

files/en-us/web/svg/attribute/requiredfeatures/index.md
This workaround doesn't work for more than a decade. Let's not talk about it.
=> Remove false workaround for detecting a SVG features

files/en-us/web/svg/content_type/index.md
Just saw this one in a list of flaws. Let's get rid of this error.
=> Fix typo creating a red broken link

files/en-us/web/svg/tutorial/svg_in_html_introduction/index.md
Cleaning up a small typo with 'via with' both being included.
Fixes a small typo.
No additional details.
=> Remove extra 'with' when referring to the img tag

files/en-us/web/svg/tutorial/gradients/index.md
Slight rewording, but most importantly it was clarified that gradient definitions can be placed in either defs elements or svg elements. See https://www.w3.org/TR/SVG/struct.html#DefsElement and https://www.w3.org/TR/SVG/struct.html#SVGElement
=> SVG Gradients

files/en-us/web/svg/attribute/conditional_processing/index.md, files/en-us/web/svg/attribute/core/index.md, files/en-us/web/svg/attribute/events/index.md, files/en-us/web/svg/attribute/overline-position/index.md, files/en-us/web/svg/attribute/overline-thickness/index.md, files/en-us/web/svg/attribute/presentation/index.md, files/en-us/web/svg/attribute/rotate/index.md, files/en-us/web/svg/attribute/strikethrough-position/index.md, files/en-us/web/svg/attribute/strikethrough-thickness/index.md, files/en-us/web/svg/attribute/styling/index.md, files/en-us/web/svg/attribute/underline-position/index.md, files/en-us/web/svg/attribute/underline-thickness/index.md
I've used `\{\{\s*SVGRef` to check the document which is missing svg sidebar under `web/svg` folder, and then add svg sidebar to those svg documents.
=> chore: add svg sidebar to all svg documents

files/en-us/web/svg/tutorial/svg_and_css/index.md
The example as-is is an invalid XML, and does not get rendered by current Firefox.
See description. The file now renders correctly.
=> Add missing xlink namespace to SVG example

package.json, yarn.lock
This PR bumps Yari to 2.28.2, which fixes a critical bug with content commands.
(I have no idea why Dependabot is not creating a PR for this...)
=> Bump @mdn/yari from 2.28.1 to 2.28.2

files/en-us/web/svg/element/feblend/index.md, files/en-us/web/svg/element/feconvolvematrix/index.md
Fixed two examples of SVG filters that were broken due to deprecated xlink attributes.
For the two examples (feBlur and feConvolveMatrix), the examples provided do not work correctly on Firefox or Chrome. They both contain linked <Image> elements with deprecated "xlink:href" attributes, which is the source of the problem. I just switched these to plain "href" and they work.
See deprecation notes on "xlink:href": [https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)
=> Fixing two broken (on Firefox) examples within SVG documentation

files/en-us/web/svg/element/mask/index.md
background is usually white in the browser
fill of the circle is default black
Black and white are also used in defining the mask, that's why I propose different colors for 'background' and the circle's fill
=> ended double use of color to prevent misunderstanding

files/en-us/web/svg/element/script/index.md
- Don't listen to the `DOMContentLoaded` event, which doesn't currently fire in the playground, and is unnecessary here if we move the `<script>` after the `<circle>`
- Also lint this codeblock
Fixes the broken example in https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script#example
Relates to https://github.com/mdn/yari/issues/9409
=> fix: svg script example didn't work in playground

files/en-us/web/svg/attribute/stroke-dasharray/index.md
Extracting out the style for strokes in this SVG to avoid line wrapping and lines can be compared visually (vertically) as we move line-by-line through the example code:
__Before:__
```html
<svg viewBox="0 0 30 12" xmlns="http://www.w3.org/2000/svg">
<line x1="0" y1="1" x2="30" y2="1" stroke="black" />
<line x1="0" y1="3" x2="30" y2="3" stroke="black" stroke-dasharray="4" />
<line x1="0" y1="5" x2="30" y2="5" stroke="black" stroke-dasharray="4 1" />
<line x1="0" y1="7" x2="30" y2="7" stroke="black" stroke-dasharray="4 1 2" />
<line
x1="0"
y1="9"
x2="30"
y2="9"
stroke="black"
stroke-dasharray="4 1 2 3" />
<line
x1="0"
y1="11"
x2="30"
y2="11"
stroke="black"
stroke-dasharray="0 4 0" />
</svg>
```
__After:__
```html
<svg viewBox="0 0 30 12" xmlns="http://www.w3.org/2000/svg">
<style>
line { …
```
=> fix(SVG): Minor rewrite of example to avoid line wrapping

files/en-us/web/svg/namespaces_crash_course/index.md
> This is done by putting the **namespace prefix and a colon** before the parameter name as shown on the `<script>` element in the example above.
The `xmlns` prefix mentioned in the content is missing. More details in #29888.
Fix #29888
=> Add missing xmlns namespace prefix

files/en-us/web/svg/element/tref/index.md
Some elements, namely `<cursor>`, `<filter>`, `<font-face-uri>`, `<glyphRef>`, and `<tref>` only work with `xlink:href`, and not `href`.
The example was incorrectly using `href` which clients, including ones that support SVG 2, will not render. I tested this in Eye of GNOME (GNOME's default image viewer.)
The SVG will now render correctly in viewers.
Compare the list of nodes that support XLink's href to the SVG 2 href:
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
Nodes that are deprecated/removed in SVG 2 do not support the SVG 2 `href` attribute, so `xlink:href` must still be used.
I was investigating this following this comment in SVGO:
* …
=> fix: tref only works with xlink:href

files/en-us/web/svg/attribute/clip/index.md
There was a typo in the `clip` attribute page.
N/A
---
=> typo: remove trailing s in clip page

files/en-us/web/svg/svg_animation_with_smil/index.md
Removed SMIL warning.
SMIL was never deprecated by Chrome or it's not even something not recommended.
Given thread itself is deprecated & 8 years old:
https://groups.google.com/a/chromium.org/g/blink-dev/c/5o0yiO440LM/m/YGEJBsjUAwAJ
=> Remove mention of SMIL being deprecated in Chrome

files/en-us/web/svg/tutorial/paths/index.md
The hyperlink looked odd with the formatting of polyline not affecting the s while the hyperlink did affect the s
The hyperlink looked odd with the formatting of <polyline> not affecting the `s` while the hyperlink did affect the `s`.
There are multiple occurrences of `<polyline>`s. Only this one is a hyperlink but all of them are formatted as codeblocks including this one & it looked odd to see that the formatting of the text does not apply to the `s` but the hyperlinking does.
=> Changed the hyperlink to not be linked to the s of polylines

files/en-us/web/svg/attribute/media/index.md
There is not glossary entry for media query.
https://developer.mozilla.org/en-US/docs/Glossary/Media/CSS was not a good match. but, the link at the bottom of that page.....
=> Minor: fix link in SVG to "media query"

files/en-us/web/svg/attribute/fill/index.md
Removed a redundant word in the text section.
Current sentence is incorrect.
--
--
=> Remove redundant word in SVG Attribute Reference: fill

files/en-us/web/svg/attribute/r/index.md
It could be helpful to add here that when set in percentage, it refers to the normalized diagonal of the SVG viewport (and not the width).
I added the information about how t "r" value is calculated when set in percentage: https://www.w3.org/TR/SVG2/coords.html#Units
https://www.w3.org/TR/SVG2/geometry.html#R
I'm making this changes because I struggled to understand why I didn't get the results I was expecting when setting a percentage value in the "r" attribute. I didn't find the info in the MDN page about the "r" attritbute.
=> Add info about the "r" attribute when set in percentage

files/en-us/web/svg/element/fedropshadow/index.md, files/en-us/web/svg/element/polygon/index.md, files/en-us/web/svg/element/polyline/index.md, files/en-us/web/svg/element/rect/index.md
Proper fix for https://github.com/mdn/content/pull/32494.
=> Fix broken links to SVG presentation attributes

files/en-us/web/svg/element/a/index.md, files/en-us/web/svg/element/circle/index.md, files/en-us/web/svg/element/clippath/index.md, files/en-us/web/svg/element/defs/index.md, files/en-us/web/svg/element/desc/index.md, files/en-us/web/svg/element/ellipse/index.md, files/en-us/web/svg/element/fedropshadow/index.md, files/en-us/web/svg/element/foreignobject/index.md, files/en-us/web/svg/element/g/index.md, files/en-us/web/svg/element/line/index.md, files/en-us/web/svg/element/lineargradient/index.md, files/en-us/web/svg/element/marker/index.md, files/en-us/web/svg/element/mask/index.md, files/en-us/web/svg/element/path/index.md, files/en-us/web/svg/element/pattern/index.md, files/en-us/web/svg/element/polygon/index.md, files/en-us/web/svg/element/polyline/index.md, files/en-us/web/svg/element/radialgradient/index.md, files/en-us/web/svg/element/rect/index.md, files/en-us/web/svg/element/script/index.md, files/en-us/web/svg/element/set/index.md, files/en-us/web/svg/element/stop/index.md, files/en-us/web/svg/element/style/index.md, files/en-us/web/svg/element/svg/index.md, files/en-us/web/svg/element/symbol/index.md, files/en-us/web/svg/element/text/index.md, files/en-us/web/svg/element/textpath/index.md, files/en-us/web/svg/element/title/index.md, files/en-us/web/svg/element/tspan/index.md, files/en-us/web/svg/element/use/index.md
As per the [SVG element template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/SVG_element_page_template), the name of the section containing the call to the `{{svginfo}}` macro is "Usage context". This is different from the "Usage notes" section we have on other reference pages to include description and working of the property/element/method.
This PR updates "Usage note" to "Usage context" for sections containing `{{svginfo}}`.
Consistency with the template
=> fix(svg elements): Update section name to match the template

files/en-us/web/svg/attribute/viewbox/index.md
Changed "top left" to "bottom left" in the SVG viewBox description
The viewBox attribute specifies the *bottom* left coordinates, not the top left.
=> Fix description of SVG viewBox

package.json
- fixes https://github.com/mdn/content/issues/33630
In order to make it work with [Corepack](https://nodejs.org/api/corepack.html) we need to have [`packageManager` field](https://nodejs.org/api/packages.html#packagemanager) in the package.json.
It doesn't affect other users.
=> feat: add 'packageManager' field for Corepack users

package.json
This adds support for `yarn start:rari` a drop in replacement for `yarn start` but using the new build system: [rari](https://github.com/mdn/rari).
The main difference is that rari uses the [new sidebars](https://github.com/mdn/content/tree/main/files/sidebars) and l10n for macros from [L10n-Template.json](https://github.com/mdn/content/blob/main/files/jsondata/L10n-Template.json).
Flaws are partially support and feedback is very much welcome.
Get feedback from writers before we switch to rari.
=> feat: add start:rari to test rari

files/en-us/web/api/dompoint/frompoint_static/index.md
Updated the code example for clarity by removing unnecessary parameters (`z` and `w`) in the `DOMPoint.fromPoint` usage.
Simplifies the example to make it more beginner-friendly and aligned with typical use cases.
Based on the MDN style guide, unnecessary complexity in examples should be avoided when not relevant to the explanation.
Fixes #39509
=> Edit DOMPoint.fromPoint_static documentation

files/en-us/web/accessibility/aria/reference/attributes/aria-busy/index.md
Description
Adds an introductory paragraph to the aria-busy attribute documentation. The new paragraph clearly explains the purpose of aria-busy as a global ARIA state that indicates when an element is being updated, helping assistive technologies understand when content is not ready to be read. It also highlights common use cases both inside and outside of ARIA live regions.
Motivation
This addition improves clarity for developers by providing a straightforward explanation of aria-busy early in the document. It helps readers better understand how and why to use the attribute effectively, enhancing accessibility implementation.
Fixes #32293
=> docs(aria-busy): add intro paragraph explaining aria-busy purpose and use cases
