- CONTRIBUTING.md
I was a bit worried about this, while reviewing #35. I had to read this a couple times to figure out what was wanted from me, as a contributor (and I already basically knew this!). Here's my attempt at a fix.
> Explain not-yet-active status in CONTRIBUTING

- .github/workflows/pr-build.yml
- package.json
- yarn.lock
Missing the updated yari (need to be published first).
> use yari's *tool* as *content* instead of redirects for validation

- package.json
- yarn.lock
Bump @mdn/yari from 0.1.150 --> 0.1.158
> upgrade @mdn/yari to 0.1.158

- README.md
Updates the `README.md` to better reflect the CLI commands for moving and deleting documents.
> update move and delete commands

- BETA.md
- README.md
As discussed, this is the addition of the beta launch document.
> adding beta launch documentation

- files/en-us/mozilla/developer_guide/introduction/index.html
fixes  #83 issue of this repository
> Fixed Bugzilla link markup

- package.json
- yarn.lock
Just because I don't want to wait for the 24h cron job that Dependabot is when it makes these kinds of upgrades.
> @mdn/yari 0.1.345

- .github/CODEOWNERS
Adds new code owners as requested by @chrisdavidmills.
> add code owners for various doc trees

- files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.html
This pull request resolves #243.
> fix: CSS causing image distortion on "Getting started with React"

- files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.html
Under the "Document Fragment" section, I felt the wording I used in this sentence was a bit more clear.
> Slight clarity improvement

- files/en-us/tools/network_monitor/performance_analysis/index.html
Removed specified image's `height` to fix bad looking style.
> Updated index.html

- files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html
Fixes: #583 a reported issue with the active learning examples on the page.
> fixing active learning examples

- files/en-us/learn/server-side/django/generic_views/index.html
Fixes https://github.com/mdn/django-locallibrary-tutorial/issues/84
This is another case arising from https://github.com/mdn/yari/issues/2198
> Improve the pagination instructions

- files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
Fixed the documentation related to the section: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features#Creating_our_new_objects
Fixes #754
> Fixed the Ball prototype method

- files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.html
> Added detail about lifecyle

- package.json
- scripts/up-to-date-check.js
Gets in your face that you haven't run `yarn install` in too long a time.
> up-to-date check script

- files/en-us/learn/javascript/building_blocks/index.html
Hello Devs, I found a very typing error. I hope you merge it in the main repository.
Regards.
> Fix_Typing_Error

- files/en-us/learn/css/howto/highlight_first_line/index.html
Re: #1080 
This is an initial how to solution, along the lines I was thinking for this section. As mentioned in the doc, I think we could happily be putting these up and over time turn that page into something more useful.
> A CSS how to example

- files/en-us/learn/javascript/first_steps/strings/index.html
renamed them as myNum2 and myString2
> fix re-declaration error of myNum and myString

- files/en-us/web/svg/attribute/begin/index.html
- files/en-us/web/svg/attribute/conditional_processing/index.html
- files/en-us/web/svg/attribute/d/index.html
- files/en-us/web/svg/attribute/fill-opacity/index.html
- files/en-us/web/svg/attribute/stroke-linejoin/index.html
- files/en-us/web/svg/attribute/stroke-opacity/index.html
- files/en-us/web/svg/content_type/index.html
- files/en-us/web/svg/element/use/index.html
Partial (quick) solution to https://github.com/mdn/yari/issues/2524
> lowercase anchor links in /Web/SVG

- files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_first_component/index.html
I replaced upper camel case in PascalCase, and hyphenated lower case in kebab-case.
> Write cases names.

- files/en-us/learn/server-side/express_nodejs/development_environment/index.html
> revise non-en_US-speling in Setting Up Node doc

- .gitignore
Add `.DS_Store` to the `.gitignore` (from conversation with @chrisdavidmills).
> add .DS_Store to .gitignore file

- files/en-us/learn/css/howto/highlight_first_line/index.html
- files/en-us/learn/css/howto/highlight_first_para/index.html
Adding another example for #1080 
Plus fixing a typo in the pseudo-elements one.
> Another learn how to example - pseudo-classes

- files/en-us/learn/css/howto/center_an_item/index.html
Another "How to" example for the CSS section.
> How to center an item

- files/en-us/learn/css/howto/add_a_shadow/index.html
Another Learn CSS example.
@chrisdavidmills I have a few of these awaiting review, once they are merged I'll go update the listing page to include them.
> How to box shadows

- files/en-us/learn/server-side/django/sessions/index.html
> UK -> US spelling in meta docs

- files/en-us/learn/accessibility/what_is_accessibility/index.html
fix typo: "246 million" instead of 246
> fixed typo in file

- files/en-us/learn/css/css_layout/positioning/index.html
To easily navigate the five types of positioning techniques in "Jump to section".
> Use h2 headings for positioning techniques

- files/en-us/learn/getting_started_with_the_web/the_web_and_web_standards/index.html
The original description gave the impression that the work of WHATWG was complete and past.
WHATWG is still very much active in working to describe the on going evolution of HTML
> Change WHATWG responsibilities to present tense

- files/en-us/learn/server-side/django/introduction/index.html
> Django intro - remove old link to expired domain

- files/en-us/learn/javascript/objects/object_prototypes/index.html
It's small but adding a comma to close https://github.com/mdn/content/issues/2152
> Tiny update

- files/en-us/learn/common_questions/what_is_a_url/index.html
> Fixes #2239

- files/en-us/learn/getting_started_with_the_web/index.html
I made this based on the flaw finding in https://github.com/mdn/yari/pull/2878
> remove links from headings in learn/getting_started_with_the_web

- files/en-us/learn/release_notes/index.html
> text revision for US English spelling

- files/en-us/learn/forms/ui_pseudo-classes/index.html
> #Fixes 2328

- files/en-us/learn/css/first_steps/how_css_works/index.html
> text revisions for US English spelling

- files/en-us/learn/css/howto/add_a_text_shadow/index.html
Another for #1080 adding a text-shadow.
> How to: text-shadow

- files/en-us/learn/css/howto/fill_a_box_with_an_image/index.html
Another how to, this one covers `object-fit`.
> how to object-fit

- files/en-us/learn/css/howto/highlight_para_after_h1/index.html
Another for #1080 this one covers combinators.
> How to using combinators

- files/en-us/learn/server-side/express_nodejs/introduction/index.html
> Revise text for US English spelling

- files/en-us/learn/accessibility/html/index.html
> update broken anchor from ARIA basics

- files/en-us/learn/server-side/express_nodejs/forms/index.html
Fixes https://github.com/mdn/sprints/issues/2026
> Drop stray express-validator/check|filter mentions

- files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html
#2533 Removed link which no longer exists
> Removed link which no longer exists, Fixes #2533

- files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.html
Remove redundant article in the sentence.
> Improve grammar

- files/en-us/learn/forms/form_validation/index.html
> Removed unhelpful link Fixes #2535

- files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.html
Corrected typo, 'sanitise/d' to 'sanitize/d'
> Fix typo on create_genre_form

- files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.html
> Fix spelling

- files/en-us/learn/accessibility/wai-aria_basics/index.html
> Revise non-en_US-spelling in WAI-ARIA basics doc

- files/en-us/web/svg/attribute/crossorigin/index.html
- files/en-us/web/svg/attribute/index.html
- files/en-us/web/svg/element/image/index.html
This PR will likely need some iterations before it can be merged.
I applied fixable flaws on the files I touched.
I'd need especially help on how to reference BCD tables using Compat macro.
Also, I'm not absolutely sure how much duplication is acceptable between SVG crossorigin and HTML crossorigin.
> 1916 svg image crossorigin

- files/en-us/learn/html/introduction_to_html/document_and_website_structure/index.html
> Updated Typo

- files/en-us/webassembly/c_to_wasm/index.html
Source must be minimal, to better focus on what we want to showcase
> Let's not add optional noise

- files/en-us/learn/css/css_layout/responsive_design/index.html
The figcaptions were empty, so unwrapped the images from the `<figure>`
> fix: Empty figure/figcaption

- .github/workflows/pr-check_redirects.yml
In case something got moved or deleted.
> run redirect checks on content change

- files/en-us/learn/server-side/django/authentication/index.html
dialogue -> dialog + adding a word for clarity
> Use US English “dialog”

- .github/ISSUE_TEMPLATE/content-bug.md
- .github/ISSUE_TEMPLATE/new-content-suggestion.md
- .github/PULL_REQUEST_TEMPLATE
We really needed some templates to help people file issues and PRs. Here they are.
> adding issue/pr templates

- files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_conditional_rendering/index.html
From:
And add a components property **about** the props property inside the component object:
To:
And add a components property **above** the props property inside the component object:
> Fix typo in “Vue conditional rendering: editing existing todos”

- .github/workflows/auto-merge.yml
This is the same as https://github.com/mdn/yari/pull/3218 but for the content repo.
> fix the auto-merge workflow

- files/en-us/web/svg/attribute/d/index.html
anticlockwise -> counterclockwise
> text revisions for US English

- files/en-us/learn/forms/how_to_structure_a_web_form/index.html
MDN article: [How to structure a web form](https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#active_learning_building_a_form_structure)
Changes in file: /en-US/docs/Learn/Forms/How_to_structure_a_web_form
Notes:
- There are three radio buttons in code example
- Update active learning's code example to finished version (wrapping inside a section element and indentantion)
> Text revision and update code to finished version

- .github/PULL_REQUEST_TEMPLATE
Fixes https://github.com/mdn/content/issues/3379 ?
> Make PR template simpler/less intimidating

- files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.html
Fixes #3423 
Adding the syntax highlighting to a block that was missing it.
> fix highlighting

- files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.html
change availabe to available on line 147
> typo: availabe to available

- files/en-us/learn/performance/perceived_performance/index.html
Also fix a couple of broken links. Fixes https://github.com/mdn/content/issues/3560
> Drop spam link from “Perceived performance” doc

- .github/workflows/pr-review-companion.yml
> correct name for credentials

- files/en-us/learn/javascript/first_steps/what_went_wrong/index.html
- Taken the list item content to it's intended list item to prevent confusion
- Added a "brush: js" class to a <pre> tag for "Math.floor(Math.random()) + 1" content in the "working through the logic" section of the article.
> fix typo on Web/JavaScript

- .github/workflows/pr-review-companion.yml
> PR review companion to not run if nothing was uploaded in the PR text

- files/en-us/learn/common_questions/set_up_a_local_testing_server/index.html
The code snippet is not contained in the proper `li`, which might confuse people.
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
> Improve document formatting

- files/en-us/learn/css/styling_text/fundamentals/index.html
Fixes https://github.com/mdn/content/issues/3872
> Fix internal link in “Fundamental text and font styling”

- files/en-us/learn/css/howto/transition_button/index.html
An example for the CSS Learn section of using transitions.
> How to transitions

- files/en-us/learn/server-side/express_nodejs/mongoose/index.html
Mongoose validator takes minLength, maxLength by preference (either is allowed). This fixes up docs to match fix in #4009.
Also moved to the "standard" note format while here.
> Fix up mongoose minLength/maxLength followup

- .github/workflows/pr-review-companion.yml
Based on https://github.com/snok/install-poetry/issues/19 and re-reading the documentation here https://github.com/snok/install-poetry#workflows-and-tips
> refactor how poetry is installed

- .github/workflows/pr-review-companion.yml
Based on https://github.com/mdn/content/pull/4174#discussion_r614917615
> hash poetry install cache based on workflow file itself

- files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> grammar error

- .github/workflows/pr-review-companion.yml
Based on https://github.com/mdn/yari/pull/3517
> set 0 cache-control on uploads in Review companion preview URLs

- files/en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors/index.html
ID Selectors -> ID selectors
MDN URL
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors
> fix case of ID selectors heading

- files/en-us/learn/server-side/express_nodejs/mongoose/index.html
Link to section was broken
No
NA
NA
> Fix broken link to section "Mongoose Primer"

- files/en-us/learn/forms/form_validation/index.html
Updated the link from .com to .io Fixes #4382 
> Fix validate.js link

- files/en-us/learn/javascript/asynchronous/introducing/index.html
At line 158, the initialize function was suppose to use the products variable declared above which was also suppose to use the let key word.
> fixed typo

- files/en-us/learn/server-side/django/forms/index.html
Fixes #4396 (Url says `/authors/10` when it should be `author/10`)
> Django: fix up URL for individual author

- files/en-us/learn/server-side/express_nodejs/development_environment/index.html
"flavours" -> flavors 
and I made an adjacent edit to shorten a sentence for readability
I see other work to do here, but I will break it up to simplify review and approval.
MDN URL
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment
> fix typos: Setting up a Node dev environment doc

- files/en-us/web/svg/attribute/letter-spacing/index.html
There were not eight elements listed.
> Fixed minor text

- .github/workflows/pr-review-companion.yml
@escattone and I are working on this. 
Trying to [unbreak the review companion](https://github.com/mdn/content/runs/2511870642?check_suite_focus=true)
> revert new --diff-file option and add debugging

- .github/workflows/pr-review-companion.yml
Hopefully getting it right this time. It's not the third attempt so in a sense I have one more chance.
> fix the --diff-file path

- files/en-us/learn/javascript/asynchronous/concepts/index.html
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts
> Adds a missing semi-colon

- .github/PULL_REQUEST_TEMPLATE
> Fixes a grammatical error in the PULL_REQUEST_TEMPLATE

- files/en-us/learn/javascript/asynchronous/timeouts_and_intervals/index.html
- Changes anonymous function to arrow function
- Supplies missing semi-colon
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals
> Slight improvements to the examples

- files/en-us/learn/javascript/asynchronous/concepts/index.html
> What was wrong/why is this fix needed?
Semi-colon missing.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts
> Adds missing semi-colons

- files/en-us/learn/server-side/django/admin_site/index.html
- files/en-us/learn/server-side/django/authentication/index.html
- files/en-us/learn/server-side/django/deployment/index.html
- files/en-us/learn/server-side/django/django_assessment_blog/index.html
- files/en-us/learn/server-side/django/forms/index.html
- files/en-us/learn/server-side/django/generic_views/index.html
- files/en-us/learn/server-side/django/home_page/index.html
- files/en-us/learn/server-side/django/introduction/index.html
- files/en-us/learn/server-side/django/sessions/index.html
- files/en-us/learn/server-side/django/skeleton_website/index.html
- files/en-us/learn/server-side/django/testing/index.html
- files/en-us/learn/server-side/django/tutorial_local_library_website/index.html
- files/en-us/learn/server-side/django/web_application_security/index.html
Fixes #4886
This makes test assertion order consistent as requested in #4886. It also fixes the "document links to itself" flaws in the module.
@chrisdavidmills Can you please merge this.
> Django Test - fix self linking and inconsistent test order

- files/en-us/learn/forms/advanced_form_styling/index.html
Fixes #4870 
Additional line in code, plus a broken link.
> fixing code and a link

- files/en-us/learn/accessibility/css_and_javascript/test_your_skills_colon__css_and_javascript_accessibility/index.html
Replace <p> and numbers 1, 2, 3, 4, with an ordered list and items
> UPDT index.html - css & js accessibility test

- files/en-us/learn/javascript/asynchronous/promises/index.html
> What was wrong/why is this fix needed?
This PR just improves two examples.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
> Converts anonymous function to arrow function

- files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.html
will allow you spend more --> will allow you to spend more
Grammar error
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started
> Add missing word

- files/en-us/tools/index.html
> Updated the menu entry Firefox 87.0 compatible

- files/en-us/learn/server-side/django/home_page/index.html
- files/en-us/learn/server-side/express_nodejs/displaying_data/locallibrary_base_template/index.html
Fixes #4370 and removes unnecessary styling to some code blocks.
> Fix statement about when sidebar will be displayed

- files/en-us/learn/javascript/asynchronous/async_await/index.html
Fixes https://github.com/mdn/content/issues/5481. Also fixes some flaws.
> Fix copypasta in async/await Learn article

- files/en-us/tools/page_inspector/how_to/work_with_animations/animation_inspector_example_colon__css_transitions/index.html
Fixes #5634
Didn't have a live sample. Now it does. 
See Preview URL
#5634
> live sample on 'Animation inspector example: CSS transitions'

- files/en-us/learn/javascript/howto/index.html
Fixes https://github.com/mdn/content/issues/5362
> Remove unlinked “how do you iterate over…” topics

- files/en-us/learn/accessibility/what_is_accessibility/index.html
Updated section for deafness to reflect cultural themes + a wider range of resources
Section was sparsely populated + did not provide sufficient resources for design; rewritten through deaf lens
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility
> update accessibility page for deafness

- files/en-us/learn/server-side/first_steps/website_security/index.html
See the following:
* https://www.schneier.com/blog/archives/2016/08/frequent_passwo.html
* https://www.ftc.gov/news-events/blogs/techftc/2016/03/time-rethink-mandatory-password-changes
...and many more places where other security advocates have pointed out that changing passwords regularly should not be encouraged (and definitely should not be made mandatory by policy). Fixes https://github.com/mdn/content/issues/5866.
> Drop suggestion about changing passwords regularly

- files/en-us/learn/html/howto/use_data_attributes/index.html
Fixes https://github.com/mdn/content/issues/5189
> Add comment to example in “Using data attributes”

- files/en-us/learn/javascript/building_blocks/test_your_skills_colon__functions/index.html
A typo error is observed on the first line of the assessment article, where 'This is change to The'
> change made to index.html

- files/en-us/learn/css/building_blocks/the_box_model/index.html
Fixes https://github.com/mdn/content/issues/5944
> Refine some wording in “The box model” doc

- files/en-us/learn/javascript/first_steps/what_is_javascript/index.html
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
Fixes awkward sentence.
Fixes #6090
> Fix sentence in topic: what is js

- files/en-us/learn/javascript/first_steps/what_is_javascript/index.html
> fix[minor]: typo

- files/en-us/learn/forms/html5_input_types/index.html
Fixes #1152 
Removes a mention that there is more information on another page, as it didn't exist. There isn't much to say about output other than what was already said, however in checking we weren't missing anything I found a nice tutorial on CSS Tricks, so linked to it.
I also removed some outdated browser information from the page.
> Tidying up the HTML5 Forms page

- files/en-us/learn/html/introduction_to_html/debugging_html/index.html
https://github.com/mdn/content/issues/6125
> Fix some language in “Debugging HTML” doc

- files/en-us/learn/html/introduction_to_html/getting_started/index.html
Instances of http were replaced with https
Fixes #6085
> Replaced  instances of http with https

- files/en-us/learn/server-side/index.html
change the MIME types to the proper glossary **title: MIME type** #6157
> fix MIME types docs has not yet written

- files/en-us/learn/css/building_blocks/the_box_model/index.html
Added this page to the ordered list at the bottom of the page so that it is consistent with surrounding pages.
> Added current page to ordered list at bottom of page

- files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.html
Fixes https://github.com/mdn/content/issues/6274
> Fix typo in “Images in HTML” doc

- files/en-us/learn/javascript/first_steps/variables/index.html
The example for why variables are useful [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables) was overly complicated.
Fixes #6226 
> Simplified example for Variables in JS

- files/en-us/learn/html/multimedia_and_embedding/index.html
Fixes https://github.com/mdn/content/issues/6315
> Fix broken link in “Multimedia and Embedding” doc

- files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/index.html
Fixes https://github.com/mdn/content/issues/6347
> Fix typo in “Video and audio content” doc

- files/en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.html
Fixes https://github.com/mdn/content/issues/6378
> Clear up some ambiguity in “Adding vector graphics to the Web”

- files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html
Fixes https://github.com/mdn/content/issues/6351
> Update outdated HTTP guidance in “other embedding technologies” doc

- files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.html
* Fix various grammar problems
* Refine some wording for greater clarity
* Remove self-link
* Fixes https://github.com/mdn/content/issues/6404
* Fixes https://github.com/mdn/content/issues/6401
* Fixes https://github.com/mdn/content/issues/6400
* Fixes https://github.com/mdn/content/issues/6398
* Fixes https://github.com/mdn/content/issues/6397
> Fix various problems in “Responsive images” article

- files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html
Fixes https://github.com/mdn/content/issues/6411
> Drop mention of frameborder from “other embedding technologies” doc

- files/en-us/learn/forms/form_validation/index.html
- The href was linked to a non-existing url.
> Link to setCustomValidity() in “Client-side form validation” doc

- files/en-us/learn/server-side/django/introduction/index.html
Changed spelling from marshall to marshal ( corrected typo)
> Update index.html to fix typo

- files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.html
Fixes https://github.com/mdn/content/issues/264
> Update YouTube info in “Third-party APIs” doc

- files/en-us/learn/html/introduction_to_html/getting_started/index.html
> Fix typo in URL fragment

- files/en-us/learn/css/first_steps/getting_started/index.html
Fixes #6537: removed an erroneous comma.
Fixes #6536: added "by"
I also removed useless non-breaking spaces (gremlins)
> Fixed punctuation error and grammar in Learn/

- files/en-us/learn/css/first_steps/how_css_is_structured/index.html
> Remove incorrect comma

- files/en-us/tools/memory/monster_example/index.html
HTML was getting rendered instead of a > 
> Fix rendering of code in “Monster example” doc

- files/en-us/learn/javascript/building_blocks/looping_code/index.html
This run on sentence was very difficult to read, so I broke it down and changed the wording a little bit to make it easier to digest.
No issue number. 
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
> Rewrite long sentence in “Looping code” doc

- files/en-us/learn/css/first_steps/getting_started/index.html
> fix typo in Learn CSS

- files/en-us/learn/css/first_steps/getting_started/index.html
A sentence misses its subject "there".
N/A
N/A
> Fix typo in Learn CSS/First Steps/Getting Started

- files/en-us/learn/css/first_steps/using_your_new_knowledge/index.html
Fixes: #6605 
Fixes: #6606 
Fixes: #6608
> Various small fixes to Learn CSS document

- files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.html
> Make it clearer (improve grammar) in Learn area

- files/en-us/learn/html/tables/structuring_planet_data/index.html
A Link to redirect user 
Fixes #6502 
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Structuring_planet_data#steps_to_complete
> Added link to point user to appropriate location

- files/en-us/learn/css/building_blocks/selectors/index.html
> fixed punctuation

- files/en-us/learn/html/introduction_to_html/the_head_metadata_in_html/index.html
Description changed to -_Now when you click anywhere **"outside"** the list_- . As per the script.js file, clicking **"on the list"** will only edit the existing list item except when the list is blank initially.
> Fix description of JS behavior

- files/en-us/learn/css/building_blocks/selectors/attribute_selectors/index.html
> improved phrasing

- files/en-us/learn/css/building_blocks/selectors/attribute_selectors/index.html
> fixed grammar

- files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.html
The original sentence's phrasing was too restrictive. We shouldn't limit ourselves to just wording that _both_ increases _and_ decreases.
No
> fixed phrasing

- files/en-us/learn/server-side/express_nodejs/displaying_data/date_formatting_using_moment/index.html
Fixes https://github.com/mdn/content/issues/6631
> Fix 404 link in “Date formatting using luxon” doc

- files/en-us/learn/javascript/building_blocks/events/index.html
Fixes https://github.com/mdn/content/issues/6657
> Document the target phase in “Introduction to events”

- files/en-us/learn/css/building_blocks/selectors/attribute_selectors/index.html
> Fix incorrect sentence in "Attribute selectors"

- files/en-us/learn/tools_and_testing/github/index.html
1) The phrase, "**This articles**" is ungrammatical.
2) **Tell** is more descriptive than **give**.
> fixed typo/grammar, improved diction

- files/en-us/learn/server-side/configuring_server_mime_types/index.html
Fixes https://github.com/mdn/content/issues/6808
> Add example of setting Content-Type header

- files/en-us/learn/javascript/objects/inheritance/index.html
Miss a ";" makes the code doesn't work in a browser console.
There is no Issue number.
> Fix code typo in “Inheritance in JavaScript” doc

- files/en-us/tools/storage_inspector/index.html
Fixes https://github.com/mdn/content/issues/6921
> Fix typo in “Storage Inspector” doc

- files/en-us/learn/css/building_blocks/the_box_model/index.html
> fixed punctuation, added clarity

- files/en-us/learn/css/building_blocks/the_box_model/index.html
1) consistent use of Oxford comma
2) other commas
3) I think "**most**" is supposed to be "**more**". If indeed "most" is meant, then the phrase would need to be amended to: "**one of the most granular of longhand properties**", or something else.
> fixed mechanics

- files/en-us/learn/css/building_blocks/handling_different_text_directions/index.html
> added clarity

- files/en-us/learn/javascript/building_blocks/events/index.html
Fixes https://github.com/mdn/content/issues/6657
> Update “Bubbling and capturing explained” in “Introduction to events” doc

- files/en-us/learn/css/building_blocks/backgrounds_and_borders/index.html
Fixes: #6982 
Fixes: #6981 
Spacing, copy editing, also removed some outdated stuff about IE9.
> Small fixes to backgrounds and borders material

- files/en-us/learn/server-side/django/authentication/index.html
> Remove unmatched parenthesis

- files/en-us/learn/css/building_blocks/organizing/index.html
> various typographical fixes

- files/en-us/tools/tools_toolbox/index.html
> Fix grammar on Toolbox/Index

- files/en-us/learn/performance/why_web_performance/index.html
Too many elements have the class.
none.
> remove unnecessary class="summary"

- files/en-us/learn/css/styling_text/styling_lists/index.html
Located in **CSS**.
Nothing to add
> (Styling lists) - various typographical fixes/improvements

- files/en-us/learn/css/styling_text/fundamentals/index.html
Located in **CSS, Styling text**
Nothing to add
> (Fundamental text and font styling) - various typographical fixes/improvements

- files/en-us/learn/css/styling_text/styling_links/index.html
> (CSS: Styling links) - various typographical fixes/improvements

- files/en-us/learn/forms/test_your_skills_colon__other_controls/index.html
Task 2 says "Comment" label (which is for task 1). Right label is "food".
> Correcting the label title at task 2, in "Other controls 2".

- files/en-us/learn/css/styling_text/styling_links/index.html
Fixes #7310 
Also fixed the notes, a flaw, removed some ableist language.
> small updates to Learn CSS Styling Links

- files/en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors/index.html
Separated the explanation of universal selector to two simple sentences for easy readability and understanding. Just an improvement of English language used.
> Simply explanation of universal selector

- files/en-us/learn/css/styling_text/typesetting_a_homepage/index.html
- Fixed mechanics: punctuation & paragraphing mostly
- Added consistent use of contractions within a paragraph
- Added emphasis on the term "**external**" in the directions
- Rewrote a poorly worded sentence
> (CSS: Typsetting a Homepage) - various typographical fixes/improvements

- files/en-us/learn/css/building_blocks/values_and_units/index.html
Let me know if you have any questions. Cheers. 🥂
> various typographical changes

- files/en-us/learn/css/styling_text/web_fonts/index.html
Google Fonts' UI has changed since these instructions were written. This PR fixes them.
Fix #7353
> Update "Using an online font service" Section

- .github/PULL_REQUEST_TEMPLATE
> Update PULL_REQUEST_TEMPLATE in GitHub actions

- files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.html
Fixes https://github.com/mdn/content/issues/7474
> Update photo-credit links for image in “How the Web works”

- .github/PULL_REQUEST_TEMPLATE
> Issue number to be fixed (ie 'Fixes #7500', if there is an associated issue)
Fixes #7500.
#123 has a lot of unnecessary references.
[`.github/PULL_REQUEST_TEMPLATE`](https://github.com/mdn/content/blob/main/.github/PULL_REQUEST_TEMPLATE) in their pull request
> update template to avoid extra references to issue

- files/en-us/learn/css/howto/create_fancy_boxes/index.html
Cannot see the shadow. add more height to make it visible
> Cannot see the shadow. add more height to make it visible

- files/en-us/learn/css/css_layout/flexbox/index.html
- Fixed mechanics: grammar, paragraphing, punctuation
- Improved diction
- Implemented consistent contractions
- Removed pleonasms
> (CSS Layout: Flexbox) various typographical fixes/improvements

- files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
- files/en-us/learn/css/building_blocks/debugging_css/index.html
- files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
Fixes: #7173 
Fixes: #7098 
Fixes: #6658 
Minor text snags, I also fixed some notecards, and the height on some examples to remove scrollbars while I was on these pages.
> Text fixes in a few Learn CSS documents

- files/en-us/tools/remote_debugging/debugging_firefox_for_android_with_webide/index.html
Fixes https://github.com/mdn/content/issues/7485
> Update Android docs link in “Debugging Firefox for Android with WebIDE”

- files/en-us/learn/javascript/first_steps/variables/index.html
> Fixed typo in doc

- files/en-us/learn/css/css_layout/floats/index.html
- Fixed mechanics
- Improved diction
- Added emphases
- Rewrote explanation about clearing content from box and wrapped content
Note: I hit a snag with Git and Github. I'm not sure if my repo or this branch are in order anymore.
> (CSS Layout: Floats) typographical improvements

- files/en-us/learn/javascript/building_blocks/test_your_skills_colon__loops/index.html
This test your skills section requires some basic DOM and object knowledge. "Loops 2" in particular is the first time objects are mentioned in the learning material so to maintain difficulty consistency I felt it would help a learner to know that accessing data inside objects has different syntax from arrays. I'm also following along with the tutorial but had prior background knowledge from other languages; a pure beginner may otherwise find the omission confusing.
> Refine the text about objects in “Test your skills: Loops” doc

- files/en-us/tools/accessibility_inspector/index.html
> Fixed typo in “Accessibility Inspector” article

- files/en-us/learn/common_questions/set_up_a_local_testing_server/index.html
Fixes #7693 
There is an unnecessary `<code>` tag and makes the text flow out.
> Remove unnecessary <code> tag

- files/en-us/learn/performance/measuring_performance/index.html
This PR fixes a few formatting issues in `learn/performance/measuring_performance`.
> Fix formatting issues in `learn/performance/measuring_performance`

- files/en-us/learn/css/css_layout/multiple-column_layout/index.html
- Fixed mechanics
- Improved phrasing
- Removed first reference to **live example** since there isn't any live example and the reader has already been provided with a document to work on in their choice of code editor
- Removed the second reference to a **live example**, except this section is in further need of correction since the reader is instructed to modify the code, but hasn't been provided with an explicit and viable means of doing so.
> (CSS Layout: Multiple-column layout) typographical improvements

- files/en-us/learn/css/css_layout/multiple-column_layout/index.html
> Fixes to Learn CSS multicol

- files/en-us/learn/performance/perceived_performance/index.html
> Fix typo in "Perceived performance" doc of Learn area

- files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.html
Fixes https://github.com/mdn/content/issues/7816
> Document switching to bash in “Setting up your own test automation…” doc

- files/en-us/learn/javascript/building_blocks/events/index.html
Fixes https://github.com/mdn/content/issues/7955
> Refine guidance on event handling in “Introduction to events”

- files/en-us/learn/css/css_layout/grids/index.html
- files/en-us/web/api/text/index.html
- Mechanics
- Diction
- Made explicit and added explanation for jargon, i.e., **tracks**
- Improved explanation of **fr** units
- Marked up terms for emphasis
> (CSS Layout: Grids) - various typographical fixes/improvements

- files/en-us/learn/javascript/building_blocks/events/index.html
Minor follow up to #7956 , as discussed in https://github.com/mdn/content/pull/7956/files#r689338411
> Intro to events - further encourage correct event handlers

- files/en-us/learn/server-side/express_nodejs/mongoose/index.html
> Fix a typo

- files/en-us/learn/server-side/django/authentication/index.html
- files/en-us/learn/server-side/django/deployment/index.html
- files/en-us/learn/server-side/django/development_environment/index.html
- files/en-us/learn/server-side/django/django_assessment_blog/index.html
- files/en-us/learn/server-side/django/forms/index.html
- files/en-us/learn/server-side/django/generic_views/index.html
- files/en-us/learn/server-side/django/home_page/index.html
- files/en-us/learn/server-side/django/introduction/index.html
- files/en-us/learn/server-side/django/models/index.html
- files/en-us/learn/server-side/django/sessions/index.html
- files/en-us/learn/server-side/django/skeleton_website/index.html
- files/en-us/learn/server-side/django/testing/index.html
- files/en-us/learn/server-side/django/web_application_security/index.html
- files/en-us/learn/server-side/express_nodejs/deployment/index.html
- files/en-us/learn/server-side/express_nodejs/displaying_data/bookinstance_detail_page_and_challenge/index.html
- files/en-us/learn/server-side/express_nodejs/mongoose/index.html
- files/en-us/learn/server-side/express_nodejs/skeleton_website/index.html
Fixing up notes so that the markdown converter can be used.
> Django/Express Fix up notes and other crud prior to markdown conversion

- files/en-us/learn/forms/test_your_skills_colon__html5_controls/index.html
JS script needs it to update the <output>
> Refine some instructions in “Test your skills: HTML5 controls”

- files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.html
Fixes #8268 
Reframed Note paragraph
> Updated Note

- files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.html
Fixes #7968
The binary installed by npm is not available in PATH. The [current recommendation](https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner.html) seems to be`npx mocha` available since npm [version 5.2 from 4 years ago](https://www.npmjs.com/package/npm?activeTab=versions) . The suggested fix is fine too. I can use that if we have a preference for it.
That's all!
> Fixes 7968 - mocha -> npx mocha

- files/en-us/learn/server-side/django/development_environment/index.html
Stated 4 databases but listed 5.
> Refine database-support language in Django “Setting up” doc

- files/en-us/learn/common_questions/what_is_a_web_server/index.html
Fixes #5881 
The fix may not be needed at all as the request is unclear and is requested in a simplified answer to a FAQ. I have created one anyway just in case reviewer thinks this is recurring and might help.
As we are looking at this file, I have also removed the section on Active Learning. It makes the article look incomplete even though it isn't.
> Fixes #5881 - adds a line about server push

- files/en-us/tools/network_monitor/index.html
Fixes #5663
We could be more specific about the type of requests the Network Monitor shows
No
> Clarify in “Network Monitor” docs: it shows only HTTP requests

- files/en-us/tools/index.html
Fixes #5408
Can't modify JS as claimed
No
> Fixes #5408 - Cannot modify JS from Tools

- files/en-us/learn/javascript/objects/test_your_skills_colon__object_basics/index.html
changing Line no. 13 of index.html
"This aim of this skill test is to assess whether you've ..."
to 
"The aim of this skill test is to assess whether you've..."
> Grammatical correction in index.html

- files/en-us/web/svg/element/animatemotion/index.html
N/A
The grammar in this article was incorrect in places
N/A
> Fix grammar in animatemotion docs

- files/en-us/web/svg/tutorial/clipping_and_masking/index.html
- files/en-us/web/svg/tutorial/gradients/index.html
- files/en-us/web/svg/tutorial/other_content_in_svg/index.html
- files/en-us/web/svg/tutorial/patterns/index.html
Fixes #8956
The screenshots were lost and they are not needed perhaps.
1. I have increased the heights a bit to remove the vscroll on wide screens
2. See https://github.com/mdn/content/pull/9160#pullrequestreview-761498820
> Hg 8956 remove SVG screenshots

- .github/PULL_REQUEST_TEMPLATE
This PR:
- formats the PR template with meaningful headings and help text hidden in comments
- adds a new metadata section, to solicit scope information from contributors
I want to learn if PR authors will provide categorical information about their changes, to facilitate content metadata and process automation.
This was heavily inspired by [BCD's PR template](https://raw.githubusercontent.com/mdn/browser-compat-data/main/.github/PULL_REQUEST_TEMPLATE.md), which has well-served BCD for several months.
I've used the template in this PR to illustrate it in use!
Historic discussions on the existing template structure:
- https://github.com/mdn/content/issues/7404
- https://github.com/mdn/content/pull/3402
> Experiment with a new PR template format

- files/jsondata/GroupData.json
The WebCodecs API sidebar links to a non-existant `AudioEncoderChunk` page. This PR updates the link to the correct name, `EncodedAudioChunk`.
> Fix sidebar link to EncodedAudioChunk

- files/jsondata/GroupData.json
This page was removed a while ago - fixes https://github.com/mdn/content/issues/9994
> Removing DocumentOrShadowRoot from sidebar

- .github/workflows/idle-issues.yml
Automatically add a label for issues and PRs which are idle.
We want to see which issues and PRs aren't active. This workflow will help us identify those issues.
> Add workflow to mark idle issues and PRs (dry run)

- .github/workflows/idle-issues.yml
Turn on the changes made in https://github.com/mdn/content/pull/10746.
> Enable labeling issues as idle

- .github/workflows/idle-issues.yml
Consolidates source for idle issue labeling to mdn/workflows.
De-duplicates the workflow. I'd like to do this for some of the others, but they're not ready yet (we need to parametrize the label name for new issues, for example). But we can do this one today.
(Please check this after merging, to make sure it still runs properly. Actions are hard to test.)
> Use reusable workflow for idle issues

- .github/workflows/idle-issues.yml
Fixes problem the loading the idle issue workflow created by https://github.com/mdn/content/pull/10929. Hopefully.
I broke it. 😞 
Here's an example of how I broke it https://github.com/mdn/content/actions/runs/1535092272
A follow-up to https://github.com/mdn/content/pull/10929.
> Fix wrong repo name in idle issues workflow

- files/jsondata/GroupData.json
Fixes https://github.com/mdn/content/issues/11223
> Remove the Transferable API from GroupData

- files/en-us/web/svg/attribute/lengthadjust/index.md
Otherwise, it will not show the last line
> Fix height of example in SVG lengthAdjust doc

- files/en-us/web/svg/element/fespotlight/index.md
> fespotlight - minor grammatical fix

- files/en-us/web/svg/attribute/keysplines/index.md
> Safari issue with fix

- files/en-us/web/svg/attribute/keytimes/index.md
https://codepen.io/yaroslav-trach/pen/VwMPprN?editors=1000
spaces in keyspline is not an issue. spaces in keytimes is.
> safari issue

- files/en-us/web/svg/attribute/keysplines/index.md
https://codepen.io/yaroslav-trach/pen/VwMPprN?editors=1000
spaces in keyspline is not an issue. spaces in keytimes is.
> Safari issue edit

- files/en-us/web/svg/element/lineargradient/index.md
Fixes https://github.com/mdn/content/issues/11794
> Fix the value type for x1,x2,y1,y2 linearGradient params

- files/en-us/web/svg/namespaces_crash_course/index.md
Fix broken link in SVG namespaces crash cource
> Fix broken link

- meta/content/en/governance/browser-compatability.md
- meta/content/en/governance/meetings.md
- meta/content/en/governance/roadmap.md
- meta/content/en/governance/roles-and-responsibilities.md
Document selection criteria and process for browsers in compat tables
Mostly, to be transparently answer https://github.com/mdn/content/issues/12742, but also to make the whole process a bit less opaque and ad hoc.
This mostly recapitulates the process we last completed with the Deno project.
* https://github.com/mdn/content/issues/12742
* https://github.com/mdn/browser-compat-data/pull/14629
> Add compat table process doc

- files/en-us/web/svg/attribute/d/index.md
Remove `#_flaws` fragment fron link.
It's for development only.
> Remove #_flaws from link

- REVIEWING.md
- files/en-us/mdn/contribute/fixing_mdn_content_bugs/index.md
- files/en-us/mdn/contribute/index.md
- files/en-us/web/http/caching/index.md
We have peeps adding issues to the old mdn/sprints repo - so I'm removing them. Most of these docs will get re-written soon anyway so I'm not spending lots of time on this, just removing
> removing links to sprints

- meta/content/en/changelog.md
- meta/content/en/writing/style/_index.md
- meta/content/en/writing/style/external-links.md
Add style guidance for external links
I've been asked a few times recently about how to handle this or that external link. This is my attempt to put my approach to external links into writing.
https://github.com/mdn/content/pull/13324
> Add style guidance for external links

- files/jsondata/GroupData.json
Fixes https://github.com/mdn/content/issues/14531
> Remove dragexit event from GroupData

- .github/workflows/system-file-changes.yml
> Fixed typos

- meta/README.md
It's meta meta documentation!
Recursion will recurse until morale improves.
This is more or less the same info as in https://github.com/mdn/content/pull/11200, but made a little more permanent.
> Add README for meta site development

- netlify.toml
Configure Netlify to skip PRs where meta is unchanged.
I think this should prevent failures as in https://github.com/mdn/content/pull/14967.
> Force Netlify to ignore PRs without meta changes

- meta/netlify.toml
One more attempt at https://github.com/mdn/content/pull/14990
> Retry ignoring PRs without meta changes

- .github/workflows/system-file-changes.yml
> system-file-changes.yml : fixed a typo

- files/en-us/web/svg/attribute/basefrequency/index.md
- files/en-us/web/svg/attribute/fy/index.md
- files/en-us/web/svg/attribute/numoctaves/index.md
- files/en-us/web/svg/attribute/requiredfeatures/index.md
- files/en-us/web/svg/attribute/seed/index.md
- files/en-us/web/svg/attribute/visibility/index.md
Fixes https://github.com/mdn/content/issues/15502.
> Fix issue 15502: fix SVG live samples

- files/jsondata/GroupData.json
There is no interface called `Canvas`.
> Fix canvas sidebar

- package.json
- yarn.lock
> Revert "Bump @mdn/yari from 0.14.57 to 0.15.1" to fix GH actions failing

- files/jsondata/GroupData.json
This method is a factory at the top level.
> Add createImageBitmap() to the Canvas API sidebar

- meta/content/en/legacy/adding-images.md
- meta/content/en/legacy/compat-tables.md
- meta/content/en/legacy/documentation-priorities.md
Extending #14055
Updates redirected URLs.
> Update redirected URLs in meta (part 45)

- .gitpod.yml
This is will make it a lot easier to quickly run a browser based IDE to contribute to the project.
> Add a basic Gitpod configuration file.

- .github/workflows/pr-check_scripts.yml
Fixes two issues with the new "Check scripts" workflow:
1. Run the workflow if its definition was changed.
2. Remove an empty job stub that I forgot to remove before merging.
The second issue might have caused a warning the next time the workflow would run.
Follow-up of https://github.com/mdn/content/pull/16911.
> Fixup check scripts workflow

- package.json
Uses yari's new binaries instead of invoking scripts from `node node_modules/@mdn/yari/` directly.
This decouples mdn/content from the implementation details of where these binaries are located in mdn/yari, and lowers the chance that yari changes break the mdn/content workflow.
> fix(scripts): use new yari-* binaries

- files/en-us/web/svg/attribute/order/index.md
The used order value `1 1 1` is not valid.
> Fix a live sample

- files/en-us/web/svg/attribute/y/index.md
I altered the grammar of some of the paragraphs on this page so they would read better.
Some of the paragraphs on this page did not read very well to me.
> Nit: Some grammatical changes to the prose

- files/en-us/web/svg/index.md
Added missing period to the end of the sentence.
> Add missing period

- .github/CODEOWNERS
The `core-yari-dev` team no longer exists, so this PR replaces the team with `core-dev`. Poking @mdn/core-dev for a review :) (cc. @schalkneethling, Github also says there is an error because `core-dev` isn't given explicit access to the `content` repo 😅)
The same fix was done in mdn/translated-content#6583
> Update team name to `core-dev` in `codeowners`

- .github/workflows/pr-review-companion.yml
Follow mdn/translated-content#6569
See: mdn/translated-content#6568.
When python version changes, this workflow may failled.
> fix: cache with specific python version

- files/en-us/web/svg/tutorial/svg_and_css/index.md
There could be a possible spelling mistake on line 460.
> Fix Spelling Mistake

- files/en-us/web/svg/attribute/y/index.md
Fix typo in Web/SVG/Attribute/y
> Fix typo in Web/SVG/Attribute/y

- files/en-us/web/svg/attribute/clippathunits/index.md
Corrected a typo
Could lead to code errors
This PR…
-->
> Fix typo in code example

- files/en-us/web/svg/content_type/index.md
> fix inline code

- files/en-us/web/svg/attribute/class/index.md
- files/en-us/web/svg/attribute/clip-rule/index.md
- files/en-us/web/svg/attribute/cursor/index.md
- files/en-us/web/svg/attribute/filterres/index.md
- files/en-us/web/svg/attribute/font-size-adjust/index.md
- files/en-us/web/svg/attribute/requiredfeatures/index.md
- files/en-us/web/svg/attribute/xlink_colon_href/index.md
- files/en-us/web/svg/attribute/xml_colon_space/index.md
- files/en-us/web/svg/element/femergenode/index.md
- files/en-us/web/svg/element/script/index.md
- files/en-us/web/svg/element/tref/index.md
Same as https://github.com/mdn/content/pull/19185, but for SVG pages.
:notebook: these are simple updates in SVG.
***
**Note:** We are simply synchronizing it with BCD. If you have objection with any compatibility status then raise an issue or PR in https://github.com/mdn/browser-compat-data repo. After BCD gets updated it'll be updated in HTML content automatically.
> SVG: update BCD Info

- files/en-us/web/svg/attribute/tabindex/index.md
Updated example to follow accessibility best practice. Fixes mdn/content#10965
> Updated example

- files/en-us/web/svg/tutorial/positions/index.md
Add alt text to canvas_default_grid.png
Relates to mdn/content#21616
> Add alt text

- files/en-us/web/svg/tutorial/getting_started/index.md
> Fix missing period at the end of the sentence

- files/en-us/web/svg/svg_as_an_image/index.md
Fix a red link in Web/SVG/SVG_as_an_Image.
> Fix a link in Web/SVG/SVG_as_an_Image

- files/en-us/web/svg/tutorial/fills_and_strokes/index.md
Relates to mdn/content#21616 
Updated line 173/174/175 https://docs.google.com/spreadsheets/d/1bUHax8ztRFt_mFaZaZAf66zdAgOVFlKMx9wMhJttQQA/edit#gid=790929018
> Add alt text for svg_stroke images

- files/en-us/web/svg/tutorial/introduction/index.md
Add comma after introductory phrases and dependent clauses. Also, change headers from h3 to h2.
Add commas to conform to comma usage guidelines and to improve readability. Change headers to make them appear in the 'In this article' section.
> Fix syntax and headings

- files/en-us/web/svg/attribute/viewbox/index.md
Adds a brief explanation of the four parameters.
[I want to publicly demonstrate my own skills to improve my chances of getting a job](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette#think_about_why_you_are_contributing_to_an_osp)
Thanks [pascualstromsnes](https://github.com/pascualstromsnes) for reporting
Fixes #3490
>  Adds parameter description. Fixes #3490 

- files/en-us/web/svg/tutorial/positions/index.md
* Minor punctuation fixes, such as adding serial commas and commas after introductory phrases.
* Use _which_ and a comma for non-restrictive clauses and _that_ for restrictive clauses.
> Make minor grammar and punctuation fixes

- files/en-us/web/svg/tutorial/getting_started/index.md
* Change header size from h3 to h2 to make the sections appear in the 'In this article' overview section.
*  Make minor punctuation fixes.
* Lowercase the word 'web' and write web server as two words. https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/web-world-wide-web-www
> Revise SVG tutorial getting started

- files/en-us/web/svg/tutorial/basic_shapes/index.md
* Add missing full stops to list items. All other list items end with a period.
* Spell out numbers from zero to nine. https://learn.microsoft.com/en-us/style-guide/numbers
> Make minor punctuation and style fixes to SVG basic shapes tutorial

- files/en-us/web/svg/tutorial/texts/index.md
* Add commas after dependent and introductory phrases.
* Use comma and _which_ for non-restrictive clauses and _that_  for restrictive clauses.
* Make list describing the attributes parallel; start each description with a verb in the third-person form — for example, _gives_ and _sets_.
> Make minor grammar fixes to SVG texts tutorial

- files/en-us/web/svg/tutorial/clipping_and_masking/index.md
* Add comma after introductory phrases and dependent clauses.
* Use comma and _which_ for non-restrictive clauses and _that_ for restrictive clauses.
* Change header size from h3 to h2.
* Simplify some text.
* Replace the more formal third person _one_ with the more informal second person _you_.
Make the tutorial more readable.
> Revise svg clipping and masking tutorial

- files/en-us/web/svg/tutorial/svg_fonts/index.md
* Provide links to PostScript and OTF definitions.
* Properly punctuate the adverbial conjunctions _however_ and _hence_.
* Add missing _than_.
* Add comma after introductory phrases.
> Make minor grammar fixes

- files/en-us/web/webdriver/index.md
updating the interaction with WebDriver code.
Please see https://github.com/mdn/content/pull/23785
This is a follow-up PR. The new code provided is updated and functional.
Updated deprecated methods with new up-to-date ones.
Supplies them with working code that they can play around with.
Please see https://github.com/mdn/content/pull/23785
> updating interaction with WebDriver code

- files/en-us/web/svg/element/fecolormatrix/index.md
https://drafts.fxtf.org/filter-effects/#elementdef-fecolormatrix
> SVG fecolormatrix attributes

- files/en-us/web/svg/attribute/restart/index.md
> Clarify value `never`

- files/en-us/web/svg/element/textpath/index.md
closes #26262,
It would be good if there was a section about `page-data` in [Content type](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type) page.
> fix(svg): replaced broken link for <path_data> in path attribute

- files/en-us/web/svg/element/fecolormatrix/index.md
`s/FillPain/FillPaint`
t
```
< FillPain
---
> FillPaint
```
> typo in <feColorMatrix> doc

- files/en-us/web/svg/tutorial/svg_in_html_introduction/index.md
Add colors so svg is not just black
This makes the code easier for beginners to understand.
> Add colors so svg is not just black

- files/en-us/web/svg/tutorial/gradients/index.md
This codepen illustrates that it works without the CDATA: https://codepen.io/sidewayss/pen/ZEVWLXR
Blame Prettier for the reformatting.
> CDATA not necessary

- files/en-us/web/svg/specification_deviations/index.md
No further explanation is needed here.
> Neutralize broken link to Gecko

- files/en-us/web/svg/attribute/transform/index.md
> fix: remove the extra bracket
